/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface CashDrawer extends HotschedulesToast.config.ToastReference {
    printer?: HotschedulesToast.config.ToastReference;
}
