/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defines whether or not the service charge is applied before (PRE) or after (POST) discounts. This field is null for non-percent service charges.
 */
export type ServiceChargeCalculation = "PRE_DISCOUNT" | "POST_DISCOUNT";

export const ServiceChargeCalculation = {
    PreDiscount: "PRE_DISCOUNT",
    PostDiscount: "POST_DISCOUNT",
} as const;
