/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Describes thresholds for when a service charge should be applied to a check.
 */
export interface ServiceChargeCriteria {
    /** The service charge is only applicable if the pre-discount check is at least this amount. */
    minCheckAmount?: number;
    /** True if the service charge is only applicable for deliveries. */
    delivery?: boolean;
    /** The service charge is waived if the pre-discount check amount is more than this amount. A `null` value means this criteria is inapplicable. */
    maxCheckAmount?: number;
    /** The service charge is only applicable to deliveries that are at least this distance. A `null` value means this criteria is inapplicable. */
    minDeliveryDistance?: number;
    /** Indicates whether the service charge is automatically applied to orders that have the takeout dining option behavior. */
    takeout?: boolean;
    /** Indicates whether the service charge is applied to orders that have the dine-in dining option behavior. */
    dineIn?: boolean;
}
