/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface PreModifier extends HotschedulesToast.config.ToastReference {
    /** The name of the pre modifier that appears in the Toast POS. */
    name?: string;
    /** True if this multiplies the modifier price, false if it adds to the modifier price. */
    scalePrice?: boolean;
    /** Amount to add to the modifier price, if scalePrice is false. Otherwise not used. */
    basePrice?: number;
    /** Amount to multiply the modifier price, if scalePrice is true. Otherwise not used. */
    scaleFactor?: number;
    /**
     * Where this premodifier should be displayed relative to the modifier name. PREFIX - before the modifier name SUFFIX - after the modifier name
     *
     */
    displayMode?: HotschedulesToast.config.PreModifierPlacement;
    parent?: HotschedulesToast.config.ToastReference;
}
