/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface Printer extends HotschedulesToast.config.ToastReference {
    /** The name of this printer. */
    name?: string;
}
