/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.labor.shifts.getAll.Response.Raw,
    HotschedulesToast.labor.Shift[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../../../..")).labor.Shift));

export declare namespace Response {
    type Raw = serializers.labor.Shift.Raw[];
}
