/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The behavior of the dining option. `TAKE_OUT` and
 * `DELIVERY` require a `customer` to be specified on the
 * order, and `DELIVERY` requires a `deliveryInfo` value.
 *
 */
export type DiningOptionBehavior = "DINEIN" | "TAKE_OUT" | "DELIVERY";

export const DiningOptionBehavior = {
    Dinein: "DINEIN",
    TakeOut: "TAKE_OUT",
    Delivery: "DELIVERY",
} as const;
