/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface DiningOption extends HotschedulesToast.config.ExternalReference {
    /** The name of the dining option. */
    name?: string;
    /**
     * The behavior of the dining option. `TAKE_OUT` and
     * `DELIVERY` require a `customer` to be specified on the
     * order, and `DELIVERY` requires a `deliveryInfo` value.
     *
     */
    behavior?: HotschedulesToast.config.DiningOptionBehavior;
    /**
     * Indicates whether the dining option has curbside behavior, and allows the guest to provide identifying information such as a description of their vehicle.
     *
     */
    curbside?: boolean;
}
