/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const CashDrawer: core.serialization.ObjectSchema<
    serializers.config.CashDrawer.Raw,
    HotschedulesToast.config.CashDrawer
> = core.serialization
    .object({
        printer: core.serialization
            .lazyObject(async () => (await import("../../../../..")).config.ToastReference)
            .optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).config.ToastReference));

export declare namespace CashDrawer {
    interface Raw extends serializers.config.ToastReference.Raw {
        printer?: serializers.config.ToastReference.Raw | null;
    }
}
