/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.labor.timeEntries.getAll.Response.Raw,
    HotschedulesToast.labor.TimeEntry[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../../../..")).labor.TimeEntry)
);

export declare namespace Response {
    type Raw = serializers.labor.TimeEntry.Raw[];
}
