/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const OrderResponse: core.serialization.ObjectSchema<
    serializers.orders.OrderResponse.Raw,
    HotschedulesToast.orders.OrderResponse
> = core.serialization.object({
    orders: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.Order))
        .optional(),
});

export declare namespace OrderResponse {
    interface Raw {
        orders?: serializers.orders.Order.Raw[] | null;
    }
}
