/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const AuthenticationToken: core.serialization.ObjectSchema<
    serializers.auth.AuthenticationToken.Raw,
    HotschedulesToast.auth.AuthenticationToken
> = core.serialization.object({
    tokenType: core.serialization.string().optional(),
    scope: core.serialization.string().optional(),
    expiresIn: core.serialization.number().optional(),
    accessToken: core.serialization.string().optional(),
    idToken: core.serialization.string().optional(),
    refreshToken: core.serialization.string().optional(),
});

export declare namespace AuthenticationToken {
    interface Raw {
        tokenType?: string | null;
        scope?: string | null;
        expiresIn?: number | null;
        accessToken?: string | null;
        idToken?: string | null;
        refreshToken?: string | null;
    }
}
