/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const AuthenticationResponse: core.serialization.ObjectSchema<
    serializers.auth.AuthenticationResponse.Raw,
    HotschedulesToast.auth.AuthenticationResponse
> = core.serialization.object({
    token: core.serialization.lazyObject(async () => (await import("../../..")).auth.AuthenticationToken).optional(),
    status: core.serialization.string().optional(),
});

export declare namespace AuthenticationResponse {
    interface Raw {
        token?: serializers.auth.AuthenticationToken.Raw | null;
        status?: string | null;
    }
}
