/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const AppliedDiscountTrigger: core.serialization.ObjectSchema<
    serializers.orders.AppliedDiscountTrigger.Raw,
    HotschedulesToast.orders.AppliedDiscountTrigger
> = core.serialization.object({
    selection: core.serialization
        .lazyObject(async () => (await import("../../../../..")).orders.ExternalReference)
        .optional(),
    quantity: core.serialization.number().optional(),
});

export declare namespace AppliedDiscountTrigger {
    interface Raw {
        selection?: serializers.orders.ExternalReference.Raw | null;
        quantity?: number | null;
    }
}
