/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const AppliedLoyaltyInfo: core.serialization.ObjectSchema<
    serializers.orders.AppliedLoyaltyInfo.Raw,
    HotschedulesToast.orders.AppliedLoyaltyInfo
> = core.serialization
    .object({
        loyaltyIdentifier: core.serialization.string().optional(),
        maskedLoyaltyIdentifier: core.serialization.string().optional(),
        vendor: core.serialization.lazy(async () => (await import("../../../../..")).orders.VendorType).optional(),
        accrualFamilyGuid: core.serialization.string().optional(),
        accrualText: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.ToastReference));

export declare namespace AppliedLoyaltyInfo {
    interface Raw extends serializers.orders.ToastReference.Raw {
        loyaltyIdentifier?: string | null;
        maskedLoyaltyIdentifier?: string | null;
        vendor?: serializers.orders.VendorType.Raw | null;
        accrualFamilyGuid?: string | null;
        accrualText?: string | null;
    }
}
