/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const AppliedTaxRate: core.serialization.ObjectSchema<
    serializers.orders.AppliedTaxRate.Raw,
    HotschedulesToast.orders.AppliedTaxRate
> = core.serialization
    .object({
        taxRateEntityType: core.serialization.property("TaxRateEntityType", core.serialization.string().optional()),
        taxRate: core.serialization
            .lazyObject(async () => (await import("../../../../..")).orders.ToastReference)
            .optional(),
        name: core.serialization.string().optional(),
        rate: core.serialization.number().optional(),
        taxAmount: core.serialization.number().optional(),
        type: core.serialization.lazy(async () => (await import("../../../../..")).orders.TaxRateType).optional(),
        facilitatorCollectAndRemitTax: core.serialization.boolean().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.ToastReference));

export declare namespace AppliedTaxRate {
    interface Raw extends serializers.orders.ToastReference.Raw {
        TaxRateEntityType?: string | null;
        taxRate?: serializers.orders.ToastReference.Raw | null;
        name?: string | null;
        rate?: number | null;
        taxAmount?: number | null;
        type?: serializers.orders.TaxRateType.Raw | null;
        facilitatorCollectAndRemitTax?: boolean | null;
    }
}
