/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const AuthorizationStateType: core.serialization.Schema<
    serializers.orders.AuthorizationStateType.Raw,
    HotschedulesToast.orders.AuthorizationStateType
> = core.serialization.enum_(["VALIDATED", "NONE", "PAID", "REVERSED", "DENIED", "ERROR", "ADJUSTING"]);

export declare namespace AuthorizationStateType {
    type Raw = "VALIDATED" | "NONE" | "PAID" | "REVERSED" | "DENIED" | "ERROR" | "ADJUSTING";
}
