/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const CardEntryModeType: core.serialization.Schema<
    serializers.orders.CardEntryModeType.Raw,
    HotschedulesToast.orders.CardEntryModeType
> = core.serialization.enum_([
    "SWIPED",
    "KEYED",
    "ONLINE",
    "EMV_CHIP_SIGN",
    "TOKENIZED",
    "PRE_AUTHED",
    "SAVED_CARD",
    "FUTURE_ORDER",
    "CONTACTLESS",
    "APPLE_PAY_CNP",
    "GOOGLE_PAY_CNP",
    "INCREMENTAL_PRE_AUTHED",
    "PARTNER_ECOM_COF",
    "CLICK_TO_PAY_CNP",
]);

export declare namespace CardEntryModeType {
    type Raw =
        | "SWIPED"
        | "KEYED"
        | "ONLINE"
        | "EMV_CHIP_SIGN"
        | "TOKENIZED"
        | "PRE_AUTHED"
        | "SAVED_CARD"
        | "FUTURE_ORDER"
        | "CONTACTLESS"
        | "APPLE_PAY_CNP"
        | "GOOGLE_PAY_CNP"
        | "INCREMENTAL_PRE_AUTHED"
        | "PARTNER_ECOM_COF"
        | "CLICK_TO_PAY_CNP";
}
