/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const CheckPaymentStatus: core.serialization.Schema<
    serializers.orders.CheckPaymentStatus.Raw,
    HotschedulesToast.orders.CheckPaymentStatus
> = core.serialization.enum_(["OPEN", "PAID", "CLOSED"]);

export declare namespace CheckPaymentStatus {
    type Raw = "OPEN" | "PAID" | "CLOSED";
}
