/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const ConfigReference: core.serialization.ObjectSchema<
    serializers.orders.ConfigReference.Raw,
    HotschedulesToast.orders.ConfigReference
> = core.serialization
    .object({
        multiLocationId: core.serialization.string().optional(),
        externalId: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.ToastReference));

export declare namespace ConfigReference {
    interface Raw extends serializers.orders.ToastReference.Raw {
        multiLocationId?: string | null;
        externalId?: string | null;
    }
}
