/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const CreditPaymentStatus: core.serialization.Schema<
    serializers.orders.CreditPaymentStatus.Raw,
    HotschedulesToast.orders.CreditPaymentStatus
> = core.serialization.enum_([
    "OPEN",
    "PROCESSING",
    "AUTHORIZED_AT_RISK",
    "AUTHORIZED",
    "ERROR",
    "ERROR_NETWORK",
    "DENIED",
    "PROCESSING_VOID",
    "VOIDED_AT_RISK",
    "CANCELLED",
    "CAPTURE_IN_PROGRESS",
    "CAPTURED",
    "VOIDED",
]);

export declare namespace CreditPaymentStatus {
    type Raw =
        | "OPEN"
        | "PROCESSING"
        | "AUTHORIZED_AT_RISK"
        | "AUTHORIZED"
        | "ERROR"
        | "ERROR_NETWORK"
        | "DENIED"
        | "PROCESSING_VOID"
        | "VOIDED_AT_RISK"
        | "CANCELLED"
        | "CAPTURE_IN_PROGRESS"
        | "CAPTURED"
        | "VOIDED";
}
