/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const CurbsidePickupInfo: core.serialization.ObjectSchema<
    serializers.orders.CurbsidePickupInfo.Raw,
    HotschedulesToast.orders.CurbsidePickupInfo
> = core.serialization
    .object({
        transportColor: core.serialization.string().optional(),
        transportDescription: core.serialization.string().optional(),
        notes: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.ToastReference));

export declare namespace CurbsidePickupInfo {
    interface Raw extends serializers.orders.ToastReference.Raw {
        transportColor?: string | null;
        transportDescription?: string | null;
        notes?: string | null;
    }
}
