/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const DeliveryInfo: core.serialization.ObjectSchema<
    serializers.orders.DeliveryInfo.Raw,
    HotschedulesToast.orders.DeliveryInfo
> = core.serialization.object({
    address1: core.serialization.string(),
    address2: core.serialization.string().optional(),
    city: core.serialization.string(),
    state: core.serialization.string(),
    zipCode: core.serialization.string(),
    latitude: core.serialization.number().optional(),
    longitude: core.serialization.number().optional(),
    notes: core.serialization.string().optional(),
    deliveredDate: core.serialization.string().optional(),
    dispatchedDate: core.serialization.string().optional(),
    deliveryEmployee: core.serialization
        .lazyObject(async () => (await import("../../../../..")).orders.ExternalReference)
        .optional(),
    deliveryState: core.serialization
        .lazy(async () => (await import("../../../../..")).orders.DeliveryState)
        .optional(),
});

export declare namespace DeliveryInfo {
    interface Raw {
        address1: string;
        address2?: string | null;
        city: string;
        state: string;
        zipCode: string;
        latitude?: number | null;
        longitude?: number | null;
        notes?: string | null;
        deliveredDate?: string | null;
        dispatchedDate?: string | null;
        deliveryEmployee?: serializers.orders.ExternalReference.Raw | null;
        deliveryState?: serializers.orders.DeliveryState.Raw | null;
    }
}
