/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const DeliveryState: core.serialization.Schema<
    serializers.orders.DeliveryState.Raw,
    HotschedulesToast.orders.DeliveryState
> = core.serialization.enum_(["PENDING", "IN_PROGRESS", "PICKED_UP", "DELIVERED"]);

export declare namespace DeliveryState {
    type Raw = "PENDING" | "IN_PROGRESS" | "PICKED_UP" | "DELIVERED";
}
