/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const DeliveryServiceInfo: core.serialization.ObjectSchema<
    serializers.orders.DeliveryServiceInfo.Raw,
    HotschedulesToast.orders.DeliveryServiceInfo
> = core.serialization
    .object({
        providerId: core.serialization.string().optional(),
        providerName: core.serialization.string().optional(),
        driverName: core.serialization.string().optional(),
        driverPhoneNumber: core.serialization.string().optional(),
        providerInfo: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.ToastReference));

export declare namespace DeliveryServiceInfo {
    interface Raw extends serializers.orders.ToastReference.Raw {
        providerId?: string | null;
        providerName?: string | null;
        driverName?: string | null;
        driverPhoneNumber?: string | null;
        providerInfo?: string | null;
    }
}
