/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Device: core.serialization.ObjectSchema<serializers.orders.Device.Raw, HotschedulesToast.orders.Device> =
    core.serialization.object({
        id: core.serialization.string().optional(),
    });

export declare namespace Device {
    interface Raw {
        id?: string | null;
    }
}
