/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const MarketplaceFacilitatorTaxInfo: core.serialization.ObjectSchema<
    serializers.orders.MarketplaceFacilitatorTaxInfo.Raw,
    HotschedulesToast.orders.MarketplaceFacilitatorTaxInfo
> = core.serialization.object({
    facilitatorCollectAndRemitTaxOrder: core.serialization.boolean().optional(),
    taxes: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.AppliedTaxRate))
        .optional(),
});

export declare namespace MarketplaceFacilitatorTaxInfo {
    interface Raw {
        facilitatorCollectAndRemitTaxOrder?: boolean | null;
        taxes?: serializers.orders.AppliedTaxRate.Raw[] | null;
    }
}
