/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const OptionGroupPricingModeType: core.serialization.Schema<
    serializers.orders.OptionGroupPricingModeType.Raw,
    HotschedulesToast.orders.OptionGroupPricingModeType
> = core.serialization.enum_(["INCLUDED", "FIXED_PRICE", "ADJUSTS_PRICE", "REPLACES_PRICE", "LOCATION_SPECIFIC_PRICE"]);

export declare namespace OptionGroupPricingModeType {
    type Raw = "INCLUDED" | "FIXED_PRICE" | "ADJUSTS_PRICE" | "REPLACES_PRICE" | "LOCATION_SPECIFIC_PRICE";
}
