/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const PaymentPropertiesType: core.serialization.Schema<
    serializers.orders.PaymentPropertiesType.Raw,
    HotschedulesToast.orders.PaymentPropertiesType
> = core.serialization.enum_([
    "CASH",
    "CREDIT",
    "GIFTCARD",
    "HOUSE_ACCOUNT",
    "REWARDCARD",
    "LEVELUP",
    "OTHER",
    "UNDETERMINED",
]);

export declare namespace PaymentPropertiesType {
    type Raw = "CASH" | "CREDIT" | "GIFTCARD" | "HOUSE_ACCOUNT" | "REWARDCARD" | "LEVELUP" | "OTHER" | "UNDETERMINED";
}
