/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const ProcessingStateType: core.serialization.Schema<
    serializers.orders.ProcessingStateType.Raw,
    HotschedulesToast.orders.ProcessingStateType
> = core.serialization.enum_(["PENDING_APPLIED", "APPLIED", "PENDING_VOID", "VOID"]);

export declare namespace ProcessingStateType {
    type Raw = "PENDING_APPLIED" | "APPLIED" | "PENDING_VOID" | "VOID";
}
