/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const ReaderType: core.serialization.Schema<
    serializers.orders.ReaderType.Raw,
    HotschedulesToast.orders.ReaderType
> = core.serialization.enum_([
    "ACS_ACR31",
    "BBPOS",
    "BBPOS_MSR",
    "IDTECH_SHUTTLE",
    "INGENICO_ICM122",
    "MAGTEK_BULLET",
    "MAGTEK_DYNAMAG",
    "MAGTEK_EDYNAMO",
    "MAGTEK_UDYNAMO",
]);

export declare namespace ReaderType {
    type Raw =
        | "ACS_ACR31"
        | "BBPOS"
        | "BBPOS_MSR"
        | "IDTECH_SHUTTLE"
        | "INGENICO_ICM122"
        | "MAGTEK_BULLET"
        | "MAGTEK_DYNAMAG"
        | "MAGTEK_EDYNAMO"
        | "MAGTEK_UDYNAMO";
}
