/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const RefundStatusType: core.serialization.Schema<
    serializers.orders.RefundStatusType.Raw,
    HotschedulesToast.orders.RefundStatusType
> = core.serialization.enum_(["NONE", "PARTIAL", "FULL"]);

export declare namespace RefundStatusType {
    type Raw = "NONE" | "PARTIAL" | "FULL";
}
