/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const RefundStrategyType: core.serialization.Schema<
    serializers.orders.RefundStrategyType.Raw,
    HotschedulesToast.orders.RefundStrategyType
> = core.serialization.enum_(["LEGACY_INCLUDE_REFUND_IN_AMOUNT_DUE", "IGNORE_REFUND_IN_AMOUNT_DUE"]);

export declare namespace RefundStrategyType {
    type Raw = "LEGACY_INCLUDE_REFUND_IN_AMOUNT_DUE" | "IGNORE_REFUND_IN_AMOUNT_DUE";
}
