/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const RemovedSelection: core.serialization.ObjectSchema<
    serializers.orders.RemovedSelection.Raw,
    HotschedulesToast.orders.RemovedSelection
> = core.serialization
    .object({
        price: core.serialization.number().optional(),
        quantity: core.serialization.number().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.ToastReference));

export declare namespace RemovedSelection {
    interface Raw extends serializers.orders.ToastReference.Raw {
        price?: number | null;
        quantity?: number | null;
    }
}
