/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const TaxInclusionType: core.serialization.Schema<
    serializers.orders.TaxInclusionType.Raw,
    HotschedulesToast.orders.TaxInclusionType
> = core.serialization.enum_(["INCLUDED", "NOT_INCLUDED", "INHERITED"]);

export declare namespace TaxInclusionType {
    type Raw = "INCLUDED" | "NOT_INCLUDED" | "INHERITED";
}
