/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const UnitofMeasureType: core.serialization.Schema<
    serializers.orders.UnitofMeasureType.Raw,
    HotschedulesToast.orders.UnitofMeasureType
> = core.serialization.enum_(["NONE", "LB", "OZ", "KG", "G"]);

export declare namespace UnitofMeasureType {
    type Raw = "NONE" | "LB" | "OZ" | "KG" | "G";
}
