/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const VendorType: core.serialization.Schema<
    serializers.orders.VendorType.Raw,
    HotschedulesToast.orders.VendorType
> = core.serialization.enum_(["TOAST", "PUNCHH", "PUNCHH2", "PAYTRONIX", "APPFRONT", "INTEGRATION"]);

export declare namespace VendorType {
    type Raw = "TOAST" | "PUNCHH" | "PUNCHH2" | "PAYTRONIX" | "APPFRONT" | "INTEGRATION";
}
