/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * When voiding something through the POS, the user must choose a preconfigured void reason.
 */
export interface VoidReason extends HotschedulesToast.config.ToastReference {
    /** The name of this void reason. */
    name?: string;
}
