/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetMenuLastModifiedTimestampRequest {
    /**
     * The identifier for the restaurant.
     */
    toastRestaurantExternalId: string;
}
