/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TableRequest {
    /**
     * The Toast POS GUID of the restaurant that the configuration
     * applies to.
     *
     */
    toastRestaurantExternalId: string;
}
