/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information about the customer loyalty program account associated with a check.
 */
export interface AppliedLoyaltyInfo extends HotschedulesToast.orders.ToastReference {
    /** An identifier for the loyalty program account. For `POST` orders, this identifier is transmitted to the loyalty program service provider to associate the check with the loyalty account. */
    loyaltyIdentifier?: string;
    /**
     * A representation of the identifier of the loyalty program
     * account that can be displayed securely. For example:
     * `************1234`. The Toast POS displays this string to
     * restaurant employees and guests.
     * You can optionally include this
     * value when you `POST` an order. It is
     * available in response data when you `GET` the order.
     * If you do not provide a `maskedLoyaltyIdentifier` when you
     * `POST` an order, this value is `null` in response data.
     * The Toast POS app displays a masked representation of the
     * `loyaltyIdentifier`. All characters except the last four
     * are hidden.
     *
     */
    maskedLoyaltyIdentifier?: string;
    /** The specific loyalty program service provider that supports the loyalty account. */
    vendor?: HotschedulesToast.orders.VendorType;
    /**
     * Response only. An internal Toast platform identifier for loyalty
     * program transactions.
     * This is not returned from the initial
     * `POST` order request and is available at a later time.
     *
     */
    accrualFamilyGuid?: string;
    /**
     * Response only. A description of the loyalty program transaction
     * to print on the customer's receipt. For example,
     * "Earned 27 points."
     * The maximum length of the description string
     * is 255 characters.
     * This is not returned from the initial
     * `POST` order request and is available at a later time.
     *
     */
    accrualText?: string;
}
