/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A service charge that is added to a check. A service charge can represent an upcharge such as a gratuity or a delivery fee. Whether the upcharge is taxable is defined in the restaurant-configured `serviceCharge`. The fields on the `AppliedServiceCharge` are calculated based on the referenced `ServiceCharge` configuration.
 *
 */
export interface AppliedServiceCharge extends HotschedulesToast.orders.ExternalReference {
    /** The final applied amount excluding tax. Required if `chargeType` is `OPEN`. */
    chargeAmount?: number;
    serviceCharge: HotschedulesToast.orders.ExternalReference;
    /**
     * The type of service charge. Response only. Valid values: * `FIXED` - The service charge is for a specific currency amount. * `PERCENT` - The service charge is for a percentage of the check amount. * `OPEN` - The service charge is not configured with an amount. The amount is specified by the restaurant employee.
     *
     */
    chargeType?: HotschedulesToast.orders.ServiceChargeType;
    /** The configured human readable label for the service charge. Response only. */
    name?: string;
    /** Whether this service charge is a delivery charge. Response only. */
    delivery?: boolean;
    /** Whether this service charge is a takeout charge. Response only. */
    takeout?: boolean;
    /** Whether this service charge is a dine-in charge. Response only. */
    dineIn?: boolean;
    /** Whether this service charge is a gratuity. Can be used to derive required tip amount on the check. Response only. */
    gratuity?: boolean;
    /** Whether this service charge is taxable. Response only. */
    taxable?: boolean;
    /** Taxes applied to the service charge. */
    appliedTaxes?: HotschedulesToast.orders.AppliedTaxRate[];
    /** For internal use only. */
    tags?: string[];
    /**
     * Defines whether a `PERCENT` service charge is applied before (`PRE_DISCOUNT`) or after (`POST_DISCOUNT`) discounts. This field is `null` for `FIXED` and `OPEN` service charges.
     *
     */
    serviceChargeCalculation?: HotschedulesToast.orders.ServiceChargeCalculation;
    refundDetails?: HotschedulesToast.orders.RefundDetails;
}
