/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A discount applied to a check or item. The Toast platform calculates service charges before it applies discounts. The system calculates tax after applying discounts. In a `POST` request, you cannot apply open percent discounts. You can apply open amount discounts. You can only apply one discount to a menu item selection. For more information, see [the _Toast Developer Guide_](https://doc.toasttab.com/doc/devguide/apiDiscountingOrders.html).
 *
 */
export interface AppliedDiscount extends HotschedulesToast.orders.ExternalReference {
    /** The name of the applied discount. Response only. */
    name?: string;
    /** The discount amount. This amount is subtracted from the check or item. */
    discountAmount?: number;
    /**
     * The amount that a discount reduces a menu item price,
     * excluding any discount amount applied to taxes.
     * In most cases, a discount only applies to the menu item price, and
     * the `nonTaxDiscountAmount` is the same as the `discountAmount`.
     * If you apply a discount to a menu item that includes tax in
     * its price, the `nonTaxDiscountAmount` is less than `discountAmount`.
     *
     */
    nonTaxDiscountAmount?: number;
    discount?: HotschedulesToast.orders.ToastReference;
    /** Optional items that triggered this discount. Response only. */
    triggers?: HotschedulesToast.orders.AppliedDiscountTrigger[];
    approver?: HotschedulesToast.orders.ExternalReference;
    /**
     * Applies to loyalty program discounts only. Loyalty
     * program reward discounts are validated and then applied,
     * or redeemed, by the third-party loyalty program service
     * provider depending on the state of the Toast platform order.
     * This value indicates the state of the discount in that
     * validation and application process. Response only.
     * Valid values:
     * <ul>
     *   <li><code>PENDING_APPLIED</code> - The loyalty program
     *   service provider confirmed that the reward discount
     *   is valid for the order and customer. The reward is not yet
     *   redeemed, or applied to the customer's loyalty
     *   account.</li>
     *   <li><code>APPLIED</code> - The reward discount is
     *   redeemed. The reward is no longer available from the
     *   customer's loyalty program account.</li>
     *   <li><code>PENDING_VOID</code> - The reward discount was
     *   removed from the Toast platform order. The reward is not
     *   available from the customer's loyalty program account
     *   until the loyalty program service provider processes
     *   the void operation.</li>
     *   <li><code>VOID</code> - The reward discount was removed
     *   from the Toast platform order and the reward is available from
     *   the customer's loyalty program account again.</li>
     * </ul>
     *
     */
    processingState?: HotschedulesToast.orders.ProcessingStateType;
    loyaltyDetails?: HotschedulesToast.orders.LoyaltyDetails;
    /** A list of menu item selections that this combo discount applies to. Empty for non-combo discounts. Response only. */
    comboItems?: HotschedulesToast.orders.ExternalReference[];
    /**
     * The promo code that was applied for this discount.
     * For a POSTed order, the Toast platform cannot validate the promo code.
     *
     */
    appliedPromoCode?: string;
    /**
     * The behavior of this discount. Valid values: * `BOGO` - Buy One, Get One. The guest receives a discount based on purchasing a specific item or items. * `PERCENT` - The guest receives a specific percentage off of the price. * `FIXED` - The guest receives a fixed currency amount off of the price. * `OPEN_PERCENT` - The guest receives a percentage off of the price. The percentage is specified when the order is placed. * `OPEN_FIXED` - The guest receives a currency amount off of the price. The amount is specified when the order is placed. * `FIXED_TOTAL` - The guest pays a specified discounted price when they purchase specific items. Also referred to as a combo discount.
     *
     */
    discountType?: HotschedulesToast.orders.DiscountBehavior;
    /** The percent value (0-100) of the applied discount when the `discountType` is `PERCENT` or `OPEN_PERCENT`. For other discount types, this value is `null`. */
    discountPercent?: number;
}
