/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates how credit card data was obtained. Response only. Valid values: * `SWIPED` - The credit card was swiped through a card reader. * `KEYED` - The restaurant employee typed the card number into a device. * `ONLINE` - The credit card information was entered online. * `EMV_CHIP_SIGN` - The credit card was inserted into a chip reader. * `TOKENIZED` - The credit card number is tokenized, meaning that it is replaced by a series of randomly generated numbers. The authorizer is able to use the token to authorize the actual credit card. * `PRE_AUTHED` - The credit card was pre-authorized for an initial amount. An example of pre-authorization is swiping a credit card to start a bar tab. The final payment is authorized when the order is complete. * `SAVED_CARD` - The credit card information was retrieved from the guest's account. * `FUTURE_ORDER` - The credit card payment was included on a scheduled order. * `CONTACTLESS` - The guest used a contactless payment option to provide the credit card number. * `APPLE_PAY_CNP` - The guest used the Apple Pay app to make the payment. * `GOOGLE_PAY_CNP` - The guest used the Google Pay app to make the payment. * `INCREMENTAL_PRE_AUTHED` - An additional payment was added to a pre-authorized card. For example, a guest uses a credit card to open a bar tab. As they continue to order more drinks, the pre-authorized amount is updated. The final payment is authorized when the order is complete. * `PARTNER_ECOM_COF` - The restaurant has the credit card on file. * `CLICK_TO_PAY_CNP` - The guest used Click to Pay to make the payment.
 *
 */
export type CardEntryModeType =
    | "SWIPED"
    | "KEYED"
    | "ONLINE"
    | "EMV_CHIP_SIGN"
    | "TOKENIZED"
    | "PRE_AUTHED"
    | "SAVED_CARD"
    | "FUTURE_ORDER"
    | "CONTACTLESS"
    | "APPLE_PAY_CNP"
    | "GOOGLE_PAY_CNP"
    | "INCREMENTAL_PRE_AUTHED"
    | "PARTNER_ECOM_COF"
    | "CLICK_TO_PAY_CNP";

export const CardEntryModeType = {
    Swiped: "SWIPED",
    Keyed: "KEYED",
    Online: "ONLINE",
    EmvChipSign: "EMV_CHIP_SIGN",
    Tokenized: "TOKENIZED",
    PreAuthed: "PRE_AUTHED",
    SavedCard: "SAVED_CARD",
    FutureOrder: "FUTURE_ORDER",
    Contactless: "CONTACTLESS",
    ApplePayCnp: "APPLE_PAY_CNP",
    GooglePayCnp: "GOOGLE_PAY_CNP",
    IncrementalPreAuthed: "INCREMENTAL_PRE_AUTHED",
    PartnerEcomCof: "PARTNER_ECOM_COF",
    ClickToPayCnp: "CLICK_TO_PAY_CNP",
} as const;
