/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The payment status of this check. Valid values: * `OPEN` - There is an outstanding balance. * `PAID` - A credit card payment was applied, but the tip has not been adjusted. * `CLOSED`  - There is no remaining amount due on this check. For credit card payments, the payment has been adjusted to reflect the tip. Toast does not prevent a `CLOSED` check from transitioning back to `OPEN` or `PAID`. Response only.
 *
 */
export type CheckPaymentStatus = "OPEN" | "PAID" | "CLOSED";

export const CheckPaymentStatus = {
    Open: "OPEN",
    Paid: "PAID",
    Closed: "CLOSED",
} as const;
