/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of credit card that was used. Response only.
 */
export type CreditCardType =
    | "VISA"
    | "MASTERCARD"
    | "AMEX"
    | "DISCOVER"
    | "JCB"
    | "DINERS"
    | "CIT"
    | "MAESTRO"
    | "LASER"
    | "SOLO"
    | "INTERAC"
    | "UNKNOWN";

export const CreditCardType = {
    Visa: "VISA",
    Mastercard: "MASTERCARD",
    Amex: "AMEX",
    Discover: "DISCOVER",
    Jcb: "JCB",
    Diners: "DINERS",
    Cit: "CIT",
    Maestro: "MAESTRO",
    Laser: "LASER",
    Solo: "SOLO",
    Interac: "INTERAC",
    Unknown: "UNKNOWN",
} as const;
