/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information that the restaurant can use to identify a guest when they arrive outside the restaurant to pick up their order. `transportDescription` is a required field.
 *
 */
export interface CurbsidePickupInfo extends HotschedulesToast.orders.ToastReference {
    /**
     * The color of the guest's vehicle if they will arrive at the restaurant in a vehicle to pick up their order.
     *
     */
    transportColor?: string;
    /**
     * Information about how the guest will arrive at the restaurant to pick up their order. For example, the make and model of the vehicle the guest will arrive in.
     *
     */
    transportDescription?: string;
    /**
     * Extra notes.
     *
     */
    notes?: string;
}
