/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface Customer extends HotschedulesToast.orders.ToastReference {
    /**
     * The first name, or given name, of the guest.
     *
     */
    firstName: string;
    /**
     * The last name, or surname, of the guest.
     *
     */
    lastName: string;
    /**
     * The telephone number of the guest.
     *
     */
    phone: string;
    /**
     * For internal use only.
     *
     */
    phoneToken?: string;
    /**
     * The email address corresponding to the guest who placed the order. The email address is the key that identifies a unique restaurant guest. All distinct guests should have distinct email addresses.
     *
     */
    email: string;
    /**
     * For internal use only.
     *
     */
    emailToken?: string;
}
