/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information related to delivery orders. Required if the dining option behavior is `DELIVERY`.
 */
export interface DeliveryInfo {
    /**
     * The first line of the street address of the delivery destination.
     *
     */
    address1: string;
    /**
     * The second line of the street address of the delivery destination.
     *
     */
    address2?: string;
    /**
     * The name of the city or town of the delivery destination.
     *
     */
    city: string;
    /**
     * The postal abbreviation of the state or province of the
     * delivery destination.
     * The abbreviation must be in ISO 3166-2
     * format (two capital letters).
     *
     */
    state: string;
    /**
     * The postal or zip code of the delivery destination.
     *
     */
    zipCode: string;
    /**
     * The north/south geographic coordinate of the delivery
     * destination, in decimal format.
     *
     */
    latitude?: number;
    /**
     * The east/west geographic coordinate of the delivery
     * destination, in decimal format.
     *
     */
    longitude?: number;
    /**
     * Additional instructions or information about the delivery.
     *
     */
    notes?: string;
    /**
     * The date and time that the delivery employee indicated in the Toast POS app that the order was delivered. Response only. This value is only set when the dining option for the order is `DELIVERY`. For other dining options, the value is `null`.
     *
     */
    deliveredDate?: string;
    /**
     * The date and time that the restaurant indicated in the Toast POS app that the order was available for delivery and assigned to a delivery employee. This value is only set when the dining option for the order is `DELIVERY`. For other dining options, the value is `null`.
     *
     */
    dispatchedDate?: string;
    deliveryEmployee?: HotschedulesToast.orders.ExternalReference;
    /**
     * An internal representation of the state of a delivery order. Valid values: * `PENDING` - The delivery is not dispatched. This corresponds to the **Unassigned** tab of the Delivery screen of the Toast POS app. * `IN_PROGRESS` - The order is on the way to the destination. This corresponds to  the **En Route** tab of the Delivery screen of the Toast POS app. * `PICKED_UP` - The employee who delivers the order has picked up the order from the restaurant. * `DELIVERED` - The order was delivered. This corresponds to the **Delivered** tab of the Delivery screen of the Toast POS app.
     *
     */
    deliveryState?: HotschedulesToast.orders.DeliveryState;
}
