/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Reserved for future use.
 *
 */
export interface DeliveryServiceInfo extends HotschedulesToast.orders.ToastReference {
    /**
     * Reserved for future use.
     *
     */
    providerId?: string;
    /**
     * Reserved for future use.
     *
     */
    providerName?: string;
    /**
     * Reserved for future use.
     *
     */
    driverName?: string;
    /**
     * Reserved for future use.
     *
     */
    driverPhoneNumber?: string;
    /**
     * Reserved for future use.
     *
     */
    providerInfo?: string;
}
