/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An internal representation of the state of a delivery order. Valid values: * `PENDING` - The delivery is not dispatched. This corresponds to the **Unassigned** tab of the Delivery screen of the Toast POS app. * `IN_PROGRESS` - The order is on the way to the destination. This corresponds to  the **En Route** tab of the Delivery screen of the Toast POS app. * `PICKED_UP` - The employee who delivers the order has picked up the order from the restaurant. * `DELIVERED` - The order was delivered. This corresponds to the **Delivered** tab of the Delivery screen of the Toast POS app.
 *
 */
export type DeliveryState = "PENDING" | "IN_PROGRESS" | "PICKED_UP" | "DELIVERED";

export const DeliveryState = {
    Pending: "PENDING",
    InProgress: "IN_PROGRESS",
    PickedUp: "PICKED_UP",
    Delivered: "DELIVERED",
} as const;
