/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The *Device ID* value that the Toast platform assigns to a specific Toast POS device. The `id` value is a unique identifier for a device. To find the ID for a Toast POS device, from the overflow  menu (⋮) select *Device Status* and then select the *Device* tab.
 *
 */
export interface Device {
    /** The physical id of the device */
    id?: string;
}
