/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The behavior of this discount. Valid values: * `BOGO` - Buy One, Get One. The guest receives a discount based on purchasing a specific item or items. * `PERCENT` - The guest receives a specific percentage off of the price. * `FIXED` - The guest receives a fixed currency amount off of the price. * `OPEN_PERCENT` - The guest receives a percentage off of the price. The percentage is specified when the order is placed. * `OPEN_FIXED` - The guest receives a currency amount off of the price. The amount is specified when the order is placed. * `FIXED_TOTAL` - The guest pays a specified discounted price when they purchase specific items. Also referred to as a combo discount.
 *
 */
export type DiscountBehavior = "BOGO" | "PERCENT" | "FIXED" | "OPEN_PERCENT" | "OPEN_FIXED" | "FIXED_TOTAL";

export const DiscountBehavior = {
    Bogo: "BOGO",
    Percent: "PERCENT",
    Fixed: "FIXED",
    OpenPercent: "OPEN_PERCENT",
    OpenFixed: "OPEN_FIXED",
    FixedTotal: "FIXED_TOTAL",
} as const;
