/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates the stage of the preparation workflow that the
 * menu item selection is in.
 * The `fulfillmentStatus` of a
 * menu item selection changes as restaurant employees move
 * the item through the functions of the Toast POS, for
 * example order entry and the kitchen display system (KDS).
 * Response only.
 * Valid values:
 * * `NEW` - The menu item selection was added to a
 *   check but is not yet sent to the KDS for
 *   preparation.
 * * `HOLD` - A restaurant employee paused the menu
 *   item selection so that it does not appear in the
 *   KDS for preparation.
 * * `SENT` - The menu item selection was fired and
 *   appears in the KDS for preparation.
 * * `READY` - Preparation is complete. The menu item
 *   selection is fulfilled and no longer appears in
 *   the KDS. If your restaurant does not use the Toast platform
 *   KDS, then order items do not reach the `READY`
 *   status.
 * </ul>
 *
 */
export type FulfillmentStatus = "NEW" | "HOLD" | "SENT" | "READY";

export const FulfillmentStatus = {
    New: "NEW",
    Hold: "HOLD",
    Sent: "SENT",
    Ready: "READY",
} as const;
