/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information about the loyalty program discount that is applied to a check. The loyalty program account is identified in the `AppliedLoyaltyInfo` value for the check.
 */
export interface LoyaltyDetails {
    /** The specific loyalty program service provider that supports the loyalty account. */
    vendor: HotschedulesToast.orders.VendorType;
    /**
     * The identifier of the loyalty program discount that
     * is recognized by the loyalty program service provider.
     * The Toast platform transmits the discount identifier to the service
     * provider to determine the validity and amount of the discount.
     *
     */
    referenceId: string;
}
