/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information about the taxes that a marketplace facilitator
 * organization remits on behalf of a Toast platform restaurant.
 * `POST` only. The orders API does not include the
 * `MarketplaceFacilitatorTaxInfo` object in response data.
 * **Note**: you can only include this information if your
 * Toast API client is associated with a designated
 * marketplace facilitator organization. Most Toast API
 * clients do not create marketplace facilitator orders.
 *
 */
export interface MarketplaceFacilitatorTaxInfo {
    /**
     * Indicates whether a marketplace facilitator organization has
     * paid the tax amounts for an order on behalf of the restaurant
     * that fulfills the order.
     * If you include this value, you indicate that the marketplace
     * facilitator order uses the prices and tax amounts calculated
     * by the Toast platform.
     * If you include this value, you *must not* include the `taxes`
     * value and you *must not* include the `externalPriceAmount`
     * for menu item selections in the order.
     *
     */
    facilitatorCollectAndRemitTaxOrder?: boolean;
    /**
     * An array of `AppliedTaxRate` objects that describe the tax
     * amounts that apply to a marketplace facilitator order.
     * If you include this value, you must include an `externalPriceAmount`
     * for each menu item selection in the order.
     *
     */
    taxes?: HotschedulesToast.orders.AppliedTaxRate[];
}
