/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information about how the modifier group affects the pricing of its parent item.
 */
export type OptionGroupPricingModeType =
    | "INCLUDED"
    | "FIXED_PRICE"
    | "ADJUSTS_PRICE"
    | "REPLACES_PRICE"
    | "LOCATION_SPECIFIC_PRICE";

export const OptionGroupPricingModeType = {
    Included: "INCLUDED",
    FixedPrice: "FIXED_PRICE",
    AdjustsPrice: "ADJUSTS_PRICE",
    ReplacesPrice: "REPLACES_PRICE",
    LocationSpecificPrice: "LOCATION_SPECIFIC_PRICE",
} as const;
