/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The payment method. When `POST`ing, only `OTHER` and `CREDIT` payment types are supported. For cash payments, you create an external cash payment type in Other Payment Options. All other types are response only. Valid values: * `CASH` - The guest paid in cash. * `CREDIT` - The guest used a credit card. * `GIFTCARD` - The guest used a gift card. * `HOUSE_ACCOUNT` - The guest used funds from their house account. * `REWARDCARD` - The guest used the available balance on a rewards card. * `LEVELUP` - The guest used the LevelUp app. * `OTHER` - The payment type is a custom type configured by the restaurant. * `UNDETERMINED` - The payment type cannot be determined.
 *
 */
export type PaymentPropertiesType =
    | "CASH"
    | "CREDIT"
    | "GIFTCARD"
    | "HOUSE_ACCOUNT"
    | "REWARDCARD"
    | "LEVELUP"
    | "OTHER"
    | "UNDETERMINED";

export const PaymentPropertiesType = {
    Cash: "CASH",
    Credit: "CREDIT",
    Giftcard: "GIFTCARD",
    HouseAccount: "HOUSE_ACCOUNT",
    Rewardcard: "REWARDCARD",
    Levelup: "LEVELUP",
    Other: "OTHER",
    Undetermined: "UNDETERMINED",
} as const;
