/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A specific pricing feature used to price out the order.
 */
export type PricingFeaturesType = "TAXESV2" | "TAXESV3";

export const PricingFeaturesType = {
    Taxesv2: "TAXESV2",
    Taxesv3: "TAXESV3",
} as const;
