/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Applies to loyalty program discounts only. Loyalty
 * program reward discounts are validated and then applied,
 * or redeemed, by the third-party loyalty program service
 * provider depending on the state of the Toast platform order.
 * This value indicates the state of the discount in that
 * validation and application process. Response only.
 * Valid values:
 * <ul>
 *   <li><code>PENDING_APPLIED</code> - The loyalty program
 *   service provider confirmed that the reward discount
 *   is valid for the order and customer. The reward is not yet
 *   redeemed, or applied to the customer's loyalty
 *   account.</li>
 *   <li><code>APPLIED</code> - The reward discount is
 *   redeemed. The reward is no longer available from the
 *   customer's loyalty program account.</li>
 *   <li><code>PENDING_VOID</code> - The reward discount was
 *   removed from the Toast platform order. The reward is not
 *   available from the customer's loyalty program account
 *   until the loyalty program service provider processes
 *   the void operation.</li>
 *   <li><code>VOID</code> - The reward discount was removed
 *   from the Toast platform order and the reward is available from
 *   the customer's loyalty program account again.</li>
 * </ul>
 *
 */
export type ProcessingStateType = "PENDING_APPLIED" | "APPLIED" | "PENDING_VOID" | "VOID";

export const ProcessingStateType = {
    PendingApplied: "PENDING_APPLIED",
    Applied: "APPLIED",
    PendingVoid: "PENDING_VOID",
    Void: "VOID",
} as const;
