/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * For internal use only.
 */
export type ReaderType =
    | "ACS_ACR31"
    | "BBPOS"
    | "BBPOS_MSR"
    | "IDTECH_SHUTTLE"
    | "INGENICO_ICM122"
    | "MAGTEK_BULLET"
    | "MAGTEK_DYNAMAG"
    | "MAGTEK_EDYNAMO"
    | "MAGTEK_UDYNAMO";

export const ReaderType = {
    AcsAcr31: "ACS_ACR31",
    Bbpos: "BBPOS",
    BbposMsr: "BBPOS_MSR",
    IdtechShuttle: "IDTECH_SHUTTLE",
    IngenicoIcm122: "INGENICO_ICM122",
    MagtekBullet: "MAGTEK_BULLET",
    MagtekDynamag: "MAGTEK_DYNAMAG",
    MagtekEdynamo: "MAGTEK_EDYNAMO",
    MagtekUdynamo: "MAGTEK_UDYNAMO",
} as const;
