/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A currency amount removed from a guest payment.
 */
export interface Refund {
    /** The amount of the refund, excluding the tip. */
    refundAmount?: number;
    /** The amount of the tip refund. */
    tipRefundAmount?: number;
    /** The date and time when the refund was made. */
    refundDate?: string;
    /** The business date (yyyyMMdd) on which this refund was created. Response only. */
    refundBusinessDate?: number;
    refundTransaction?: HotschedulesToast.orders.ToastReference;
    /**
     * For internal use only.
     *
     */
    refundStrategy?: HotschedulesToast.orders.RefundStrategyType;
}
