/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * For internal use only.
 *
 */
export interface RemovedSelection extends HotschedulesToast.orders.ToastReference {
    /** For internal use only. */
    price?: number;
    /** For internal use only. */
    quantity?: number;
}
