/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specifies whether this selection is a special request or other off-menu sale. If `null` or `NONE`, describes a normal modifier or item selection.
 *
 */
export type SelectionType = "NONE" | "OPEN_ITEM" | "SPECIAL_REQUEST" | "PORTION" | "HOUSE_ACCOUNT_PAY_BALANCE";

export const SelectionType = {
    None: "NONE",
    OpenItem: "OPEN_ITEM",
    SpecialRequest: "SPECIAL_REQUEST",
    Portion: "PORTION",
    HouseAccountPayBalance: "HOUSE_ACCOUNT_PAY_BALANCE",
} as const;
