/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A wrapper object with fields that allow reference to a Toast entity by Toast GUID.
 */
export interface ToastReference {
    /** The GUID maintained by the Toast platform. */
    guid: string;
    /** The type of object this is. Response only. */
    referemceEntityType: string;
}
