/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unit of measure required for weighing the item. The default is `NONE`, which means that the item is not meant to be weighed.
 *
 */
export type UnitofMeasureType = "NONE" | "LB" | "OZ" | "KG" | "G";

export const UnitofMeasureType = {
    None: "NONE",
    Lb: "LB",
    Oz: "OZ",
    Kg: "KG",
    G: "G",
} as const;
