/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The specific loyalty program service provider that supports the loyalty account.
 */
export type VendorType = "TOAST" | "PUNCHH" | "PUNCHH2" | "PAYTRONIX" | "APPFRONT" | "INTEGRATION";

export const VendorType = {
    Toast: "TOAST",
    Punchh: "PUNCHH",
    Punchh2: "PUNCHH2",
    Paytronix: "PAYTRONIX",
    Appfront: "APPFRONT",
    Integration: "INTEGRATION",
} as const;
