/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information about a void applied to a check or item.
 */
export interface VoidInformation {
    voidUser?: HotschedulesToast.orders.ExternalReference;
    voidApprover?: HotschedulesToast.orders.ExternalReference;
    /** The date on which the void was made. */
    voidDate?: string;
    /** The business date (yyyyMMdd) on which the void was made. Response only. */
    voidBusinessDate?: number;
    voidReason?: HotschedulesToast.orders.ExternalReference;
}
