/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Image: core.serialization.ObjectSchema<serializers.config.Image.Raw, HotschedulesToast.config.Image> =
    core.serialization.object({
        url: core.serialization.string().optional(),
    });

export declare namespace Image {
    interface Raw {
        url?: string | null;
    }
}
