/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const MenuDisplay: core.serialization.Schema<
    serializers.config.MenuDisplay.Raw,
    HotschedulesToast.config.MenuDisplay
> = core.serialization.enum_(["ALL", "POS_ONLY", "NONE"]);

export declare namespace MenuDisplay {
    type Raw = "ALL" | "POS_ONLY" | "NONE";
}
