/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const TaxTableRow: core.serialization.ObjectSchema<
    serializers.config.TaxTableRow.Raw,
    HotschedulesToast.config.TaxTableRow
> = core.serialization.object({
    start: core.serialization.number().optional(),
    end: core.serialization.number().optional(),
    tax: core.serialization.number().optional(),
    pattern: core.serialization.boolean().optional(),
});

export declare namespace TaxTableRow {
    interface Raw {
        start?: number | null;
        end?: number | null;
        tax?: number | null;
        pattern?: boolean | null;
    }
}
