/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface BreakType extends HotschedulesToast.config.ToastReference {
    /**
     * The name of the work break type, as recognized by
     * restaurant employees.
     *
     */
    name?: string;
    /**
     * Indicates whether the break is available and can be taken
     * by restaurant employees.
     *
     */
    active?: boolean;
    /** Indicates whether the break is paid. */
    paid?: boolean;
    /** The duration of the break in minutes. */
    duration?: number;
    /**
     * Indicates whether the duration is enforced as the minimum
     * time for the break.
     *
     */
    enforceMinimumTime?: boolean;
    /**
     * True if breaks that are not taken within the specified break
     * interval should be generated in Toast.
     *
     */
    trackMissedBreaks?: boolean;
    /**
     * The number of hours between break intervals. Break intervals
     * are specified in hours and minutes. If missed breaks are not
     * tracked, this value may be null.
     *
     */
    breakIntervalHrs?: number;
    /**
     * The number of minutes between break intervals. Break intervals
     * are specified in hours and minutes. If missed breaks are not
     * tracked, this value may be null.
     *
     */
    breakIntervalMins?: number;
    /**
     * Indicates whether break acknowledgements are collected for
     * this type of break. Break acknowledgements will not be
     * collected if `trackMissedBreaks` is false.
     *
     */
    trackBreakAcknowledgement?: boolean;
}
