/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface MenuItem extends HotschedulesToast.config.ExternalReference {
    /**
     * The name of the menu item as it appears in the Toast POS.
     *
     */
    name?: string;
    /**
     * The amount of food energy in the item, expressed in
     * Calorie units. Values can be positive, negative, or zero.
     *
     */
    calories?: number;
    /** The stock keeping unit (SKU) code for the item. */
    sku?: string;
    /** The price look up (PLU) code for the item. */
    plu?: string;
    /**
     * Deprecated. Indicates whether restaurant guests can order from the menu online. Toast is streamlining and improving the set of configuration options that restaurants use for configuring whether a menu entity can be ordered online. As part of this change, the `orderableOnline` value has been deprecated. Before 2020-05-25, you should transition to using the `visibility` array that the menus API returns for each menu entity, instead of this `orderableOnline` value, to determine if the entity should be available for online ordering. See <a href="https://doc.toasttab.com/doc/devguide/apiDeprecatedApiFunctions.html#apiMenuEntityVisibilityEnhancements">Menu entity visibility enhancements (rolled out)</a> for more information.
     *
     */
    orderableOnline?: string;
    /**
     * Deprecated. Indicates where the menu is displayed and who can see it. * ALL: Visible to everyone (servers and customers) * POS_ONLY: Only visible to servers * NONE: Hidden from everyone Toast is streamlining and improving the set of configuration options that restaurants use for configuring where a menu entity is visible (for example, on a Toast POS device or on a restaurant's Toast online ordering website). As part of this change, the `visibility` value in the configuration API has been deprecated. Before 2020-05-25, you should transition to using the `visibility` array that the menus API returns for each menu entity, instead of this `visibility` value, to determine where the entity should be visible. See <a href="https://doc.toasttab.com/doc/devguide/apiDeprecatedApiFunctions.html#apiMenuEntityVisibilityEnhancements">Menu entity visibility enhancements (rolled out)</a> for more information.
     *
     */
    visibility?: HotschedulesToast.config.MenuDisplay;
    /**
     * Specifies whether this item is a special request or other off-menu transaction. * `NONE` - a normal menu item or modifier. * `OPENITEM` - an item that is not on a menu. * `SPECIAL_REQUEST` - a selection that is not an item. * `PORTION` - a division of a menu item used to apply modifiers separately to separate parts of an item. For example, one half of a pizza.
     *
     */
    type?: HotschedulesToast.config.SpecialRequestSelection;
    /**
     * An array of `ExternalReference` objects containing the
     * identifiers of the `MenuOptionGroup`s
     * that contain modifiers applicable to this item. Does not
     * include those inherited from the parent `MenuGroup`.
     *
     */
    optionGroups?: HotschedulesToast.config.ExternalReference[];
    /**
     * True if this menu item inherits `MenuOptionGroup`s
     * from its parent `MenuGroup`.
     *
     */
    inheritOptionGroups?: boolean;
    /**
     * An array of `Image`
     * objects that are associated with the `MenuItem`.
     *
     */
    images?: HotschedulesToast.config.Image[];
    /**
     * The unit of measure used to determine the price of the item.
     * The default is NONE.
     * This value is not relevant if `inheritUnitOfMeasure` is true.
     *
     */
    unitOfMeasure?: HotschedulesToast.config.PriceUnit;
    /**
     * True if this menu item inherits its unit of measure
     * from its parent `MenuGroup`.
     *
     */
    inheritUnitOfMeasure?: boolean;
}
