/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specifies whether this item is a special request or other off-menu transaction. * `NONE` - a normal menu item or modifier. * `OPENITEM` - an item that is not on a menu. * `SPECIAL_REQUEST` - a selection that is not an item. * `PORTION` - a division of a menu item used to apply modifiers separately to separate parts of an item. For example, one half of a pizza.
 *
 */
export type SpecialRequestSelection = "NONE" | "OPENITEM" | "SPECIAL_REQUEST" | "PORTION";

export const SpecialRequestSelection = {
    None: "NONE",
    Openitem: "OPENITEM",
    SpecialRequest: "SPECIAL_REQUEST",
    Portion: "PORTION",
} as const;
