/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Shift: core.serialization.ObjectSchema<serializers.labor.Shift.Raw, HotschedulesToast.labor.Shift> =
    core.serialization
        .object({
            createdDate: core.serialization.string().optional(),
            modifiedDate: core.serialization.string().optional(),
            deletedDate: core.serialization.string().optional(),
            deleted: core.serialization.boolean().optional(),
            jobReference: core.serialization
                .lazyObject(async () => (await import("../../../../..")).labor.ExternalReference)
                .optional(),
            employeeReference: core.serialization
                .lazyObject(async () => (await import("../../../../..")).labor.ExternalReference)
                .optional(),
            inDate: core.serialization.string().optional(),
            outDate: core.serialization.string().optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).labor.ExternalReference));

export declare namespace Shift {
    interface Raw extends serializers.labor.ExternalReference.Raw {
        createdDate?: string | null;
        modifiedDate?: string | null;
        deletedDate?: string | null;
        deleted?: boolean | null;
        jobReference?: serializers.labor.ExternalReference.Raw | null;
        employeeReference?: serializers.labor.ExternalReference.Raw | null;
        inDate?: string | null;
        outDate?: string | null;
    }
}
