/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ShiftsRequest {
    /**
     * An optional identifier that filters return values for a
     * specific shift. The identifier can be a Toast platform GUID
     * or an external identifier. If present, the shifts
     * resource will only return the shifts you specify. You
     * can include multiple `shiftIds` query parameters (maximum
     * 100).
     *
     */
    shiftIds?: string;
    /**
     * Optional start date and time of time period to match
     * shifts. A shift matches the time period if the shift
     * `inDate` is after (inclusive) the specified `startDate` and
     * the shift `outDate` is before the `endDate` (exclusive).
     * These parameters are required if the `shiftIds` parameter
     * is not defined. The specified period cannot be longer than
     * one month.
     *
     */
    startDate?: string;
    /**
     * Optional end date and time of time period to match shifts.
     * A shift matches the time period if the shift `inDate` is
     * after (inclusive) the specified `startDate` and the shift
     * `outDate` is before the `endDate` (exclusive). These
     * parameters are required if the `shiftIds` parameter is not
     * defined. The specified period cannot be longer than one
     * month.
     *
     */
    endDate?: string;
    /**
     * The Toast platform GUID of the restaurant that is the
     * context for this operation.
     *
     */
    toastRestaurantExternalId: string;
}
