/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const AuthenticationRequest: core.serialization.ObjectSchema<
    serializers.auth.AuthenticationRequest.Raw,
    HotschedulesToast.auth.AuthenticationRequest
> = core.serialization.object({
    clientId: core.serialization.string().optional(),
    clientSecret: core.serialization.string().optional(),
    userAccessType: core.serialization.string().optional(),
});

export declare namespace AuthenticationRequest {
    interface Raw {
        clientId?: string | null;
        clientSecret?: string | null;
        userAccessType?: string | null;
    }
}
