/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Discounts } from "../resources/discounts/client/Client";
import { Orders as Orders_ } from "../resources/orders/client/Client";
import { Payments } from "../resources/payments/client/Client";

export declare namespace Orders {
    interface Options {
        environment?: environments.HotschedulesToastEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class Orders {
    constructor(private readonly options: Orders.Options) {}

    private _discounts: Discounts | undefined;

    public get discounts(): Discounts {
        return (this._discounts ??= new Discounts(this.options));
    }

    private _orders: Orders_ | undefined;

    public get orders(): Orders_ {
        return (this._orders ??= new Orders_(this.options));
    }

    private _payments: Payments | undefined;

    public get payments(): Payments {
        return (this._payments ??= new Payments(this.options));
    }
}
