/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface PreModifierGroup extends HotschedulesToast.config.ToastReference {
    /** The name of the pre modifier that appears in the Toast POS. */
    name?: string;
    /**
     * True if this PreModifierGroup is set as the default Group.
     * Only a single PreModifierGroup can be set as default at one time.
     *
     */
    isDefault?: boolean;
}
