/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Employees } from "../resources/employees/client/Client";
import { Jobs } from "../resources/jobs/client/Client";
import { Shifts } from "../resources/shifts/client/Client";
import { TimeEntries } from "../resources/timeEntries/client/Client";

export declare namespace Labor {
    interface Options {
        environment?: environments.HotschedulesToastEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class Labor {
    constructor(private readonly options: Labor.Options) {}

    private _employees: Employees | undefined;

    public get employees(): Employees {
        return (this._employees ??= new Employees(this.options));
    }

    private _jobs: Jobs | undefined;

    public get jobs(): Jobs {
        return (this._jobs ??= new Jobs(this.options));
    }

    private _shifts: Shifts | undefined;

    public get shifts(): Shifts {
        return (this._shifts ??= new Shifts(this.options));
    }

    private _timeEntries: TimeEntries | undefined;

    public get timeEntries(): TimeEntries {
        return (this._timeEntries ??= new TimeEntries(this.options));
    }
}
