/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface NoSaleReason extends HotschedulesToast.config.ToastReference {
    /** The name of the no sale reason that appears in the Toast POS. */
    name?: string;
}
