/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const Availability: core.serialization.ObjectSchema<
    serializers.menus.Availability.Raw,
    HotschedulesToast.menus.Availability
> = core.serialization.object({});

export declare namespace Availability {
    interface Raw {}
}
