/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const DaysOfWeek: core.serialization.Schema<
    serializers.menus.DaysOfWeek.Raw,
    HotschedulesToast.menus.DaysOfWeek
> = core.serialization.enum_(["SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY"]);

export declare namespace DaysOfWeek {
    type Raw = "SUNDAY" | "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY";
}
