/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const MenuEntityVisibility: core.serialization.Schema<
    serializers.menus.MenuEntityVisibility.Raw,
    HotschedulesToast.menus.MenuEntityVisibility
> = core.serialization.enum_(["POS", "KIOSK", "GRUBHUB", "TOAST_ONLINE_ORDERING", "ORDERING_PARTNERS"]);

export declare namespace MenuEntityVisibility {
    type Raw = "POS" | "KIOSK" | "GRUBHUB" | "TOAST_ONLINE_ORDERING" | "ORDERING_PARTNERS";
}
