/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const Metadata: core.serialization.ObjectSchema<
    serializers.menus.Metadata.Raw,
    HotschedulesToast.menus.Metadata
> = core.serialization.object({
    restaurantGuid: core.serialization.string().optional(),
    lastUpdated: core.serialization.string().optional(),
});

export declare namespace Metadata {
    interface Raw {
        restaurantGuid?: string | null;
        lastUpdated?: string | null;
    }
}
