/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const ModifierOption: core.serialization.ObjectSchema<
    serializers.menus.ModifierOption.Raw,
    HotschedulesToast.menus.ModifierOption
> = core.serialization.object({
    referenceId: core.serialization.number().optional(),
    name: core.serialization.string().optional(),
    guid: core.serialization.string().optional(),
    multiLocationId: core.serialization.string().optional(),
    masterId: core.serialization.number().optional(),
    description: core.serialization.string().optional(),
    image: core.serialization.string().optional(),
    visibility: core.serialization
        .list(core.serialization.lazy(async () => (await import("../../..")).menus.MenuEntityVisibility))
        .optional(),
    price: core.serialization.number().optional(),
    pricingStrategy: core.serialization.string().optional(),
    pricingRules: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).menus.PricingRules))
        .optional(),
    salesCategory: core.serialization.lazyObject(async () => (await import("../../..")).menus.SalesCategory).optional(),
    taxInfo: core.serialization.list(core.serialization.string()).optional(),
    modifierOptionTaxInfo: core.serialization
        .lazyObject(async () => (await import("../../..")).menus.ModifierOptionTaxInfo)
        .optional(),
    itemTags: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).menus.ItemTag))
        .optional(),
    plu: core.serialization.string().optional(),
    sku: core.serialization.string().optional(),
    calories: core.serialization.number().optional(),
    contentAdvisories: core.serialization
        .lazyObject(async () => (await import("../../..")).menus.ContentAdvisories)
        .optional(),
    unitOfMeasure: core.serialization.lazy(async () => (await import("../../..")).menus.PriceUnit).optional(),
    isDefault: core.serialization.boolean().optional(),
    allowsDuplicates: core.serialization.boolean().optional(),
    portions: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).menus.Portion))
        .optional(),
    modifierGroupReferences: core.serialization.list(core.serialization.number()).optional(),
});

export declare namespace ModifierOption {
    interface Raw {
        referenceId?: number | null;
        name?: string | null;
        guid?: string | null;
        multiLocationId?: string | null;
        masterId?: number | null;
        description?: string | null;
        image?: string | null;
        visibility?: serializers.menus.MenuEntityVisibility.Raw[] | null;
        price?: number | null;
        pricingStrategy?: string | null;
        pricingRules?: serializers.menus.PricingRules.Raw[] | null;
        salesCategory?: serializers.menus.SalesCategory.Raw | null;
        taxInfo?: string[] | null;
        modifierOptionTaxInfo?: serializers.menus.ModifierOptionTaxInfo.Raw | null;
        itemTags?: serializers.menus.ItemTag.Raw[] | null;
        plu?: string | null;
        sku?: string | null;
        calories?: number | null;
        contentAdvisories?: serializers.menus.ContentAdvisories.Raw | null;
        unitOfMeasure?: serializers.menus.PriceUnit.Raw | null;
        isDefault?: boolean | null;
        allowsDuplicates?: boolean | null;
        portions?: serializers.menus.Portion.Raw[] | null;
        modifierGroupReferences?: number[] | null;
    }
}
