/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const ModifierGroupBehavior: core.serialization.Schema<
    serializers.menus.ModifierGroupBehavior.Raw,
    HotschedulesToast.menus.ModifierGroupBehavior
> = core.serialization.enum_(["REQUIRED", "OPTIONAL_FORCE_SHOW", "OPTIONAL"]);

export declare namespace ModifierGroupBehavior {
    type Raw = "REQUIRED" | "OPTIONAL_FORCE_SHOW" | "OPTIONAL";
}
