/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const ModifierOptionTaxInfo: core.serialization.ObjectSchema<
    serializers.menus.ModifierOptionTaxInfo.Raw,
    HotschedulesToast.menus.ModifierOptionTaxInfo
> = core.serialization.object({
    taxRateGuids: core.serialization.list(core.serialization.string()).optional(),
    overrideItemTaxRates: core.serialization.boolean().optional(),
});

export declare namespace ModifierOptionTaxInfo {
    interface Raw {
        taxRateGuids?: string[] | null;
        overrideItemTaxRates?: boolean | null;
    }
}
