/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const Portion: core.serialization.ObjectSchema<serializers.menus.Portion.Raw, HotschedulesToast.menus.Portion> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        guid: core.serialization.string().optional(),
        modifierGroupReferences: core.serialization.list(core.serialization.number()).optional(),
    });

export declare namespace Portion {
    interface Raw {
        name?: string | null;
        guid?: string | null;
        modifierGroupReferences?: number[] | null;
    }
}
