/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const PreModifierGroup: core.serialization.ObjectSchema<
    serializers.menus.PreModifierGroup.Raw,
    HotschedulesToast.menus.PreModifierGroup
> = core.serialization.object({
    name: core.serialization.string().optional(),
    guid: core.serialization.string().optional(),
    preModifiers: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).menus.PreModifier))
        .optional(),
});

export declare namespace PreModifierGroup {
    interface Raw {
        name?: string | null;
        guid?: string | null;
        preModifiers?: serializers.menus.PreModifier.Raw[] | null;
    }
}
