/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const PricingRules: core.serialization.ObjectSchema<
    serializers.menus.PricingRules.Raw,
    HotschedulesToast.menus.PricingRules
> = core.serialization.object({
    timeSpecificPricingRules: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).menus.TimeSpecificPrice))
        .optional(),
    sizeSpecificPricingGuid: core.serialization.string().optional(),
    sizeSequencePricingRules: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).menus.SizeSequencePricingRule))
        .optional(),
});

export declare namespace PricingRules {
    interface Raw {
        timeSpecificPricingRules?: serializers.menus.TimeSpecificPrice.Raw[] | null;
        sizeSpecificPricingGuid?: string | null;
        sizeSequencePricingRules?: serializers.menus.SizeSequencePricingRule.Raw[] | null;
    }
}
