/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const SequencePrice: core.serialization.ObjectSchema<
    serializers.menus.SequencePrice.Raw,
    HotschedulesToast.menus.SequencePrice
> = core.serialization.object({
    sequence: core.serialization.number().optional(),
    price: core.serialization.number().optional(),
});

export declare namespace SequencePrice {
    interface Raw {
        sequence?: number | null;
        price?: number | null;
    }
}
