/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const SizeSequencePricingRule: core.serialization.ObjectSchema<
    serializers.menus.SizeSequencePricingRule.Raw,
    HotschedulesToast.menus.SizeSequencePricingRule
> = core.serialization.object({
    sizeName: core.serialization.string().optional(),
    sizeGuid: core.serialization.string().optional(),
    sequencePrices: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).menus.SequencePrice))
        .optional(),
});

export declare namespace SizeSequencePricingRule {
    interface Raw {
        sizeName?: string | null;
        sizeGuid?: string | null;
        sequencePrices?: serializers.menus.SequencePrice.Raw[] | null;
    }
}
