/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../core";

export const TimeRange: core.serialization.ObjectSchema<
    serializers.menus.TimeRange.Raw,
    HotschedulesToast.menus.TimeRange
> = core.serialization.object({
    start: core.serialization.string().optional(),
    end: core.serialization.string().optional(),
});

export declare namespace TimeRange {
    interface Raw {
        start?: string | null;
        end?: string | null;
    }
}
