/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const DiscountType: core.serialization.Schema<
    serializers.config.DiscountType.Raw,
    HotschedulesToast.config.DiscountType
> = core.serialization.enum_(["PERCENT", "FIXED", "OPEN_PERCENT", "OPEN_FIXED", "BOGO", "FIXED_TOTAL"]);

export declare namespace DiscountType {
    type Raw = "PERCENT" | "FIXED" | "OPEN_PERCENT" | "OPEN_FIXED" | "BOGO" | "FIXED_TOTAL";
}
