/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const MenuSelection: core.serialization.Schema<
    serializers.config.MenuSelection.Raw,
    HotschedulesToast.config.MenuSelection
> = core.serialization.enum_(["FIRST", "LEAST_EXPENSIVE", "MOST_EXPENSIVE"]);

export declare namespace MenuSelection {
    type Raw = "FIRST" | "LEAST_EXPENSIVE" | "MOST_EXPENSIVE";
}
