/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const ServiceChargeCriteria: core.serialization.ObjectSchema<
    serializers.config.ServiceChargeCriteria.Raw,
    HotschedulesToast.config.ServiceChargeCriteria
> = core.serialization.object({
    minCheckAmount: core.serialization.number().optional(),
    delivery: core.serialization.boolean().optional(),
    maxCheckAmount: core.serialization.number().optional(),
    minDeliveryDistance: core.serialization.number().optional(),
    takeout: core.serialization.boolean().optional(),
    dineIn: core.serialization.boolean().optional(),
});

export declare namespace ServiceChargeCriteria {
    interface Raw {
        minCheckAmount?: number | null;
        delivery?: boolean | null;
        maxCheckAmount?: number | null;
        minDeliveryDistance?: number | null;
        takeout?: boolean | null;
        dineIn?: boolean | null;
    }
}
