/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const ServiceChargeCalculation: core.serialization.Schema<
    serializers.config.ServiceChargeCalculation.Raw,
    HotschedulesToast.config.ServiceChargeCalculation
> = core.serialization.enum_(["PRE_DISCOUNT", "POST_DISCOUNT"]);

export declare namespace ServiceChargeCalculation {
    type Raw = "PRE_DISCOUNT" | "POST_DISCOUNT";
}
