/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A set of items that will be grouped together in sales reports. SalesCategories can be applied at any level, from entire menus to individual menu items.
 */
export interface SalesCategory extends HotschedulesToast.config.ToastReference {
    /** The name of this sales category. */
    name?: string;
}
