/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.orders.discounts.get.Response.Raw,
    HotschedulesToast.orders.ApplicableDiscount[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../../../..")).orders.ApplicableDiscount)
);

export declare namespace Response {
    type Raw = serializers.orders.ApplicableDiscount.Raw[];
}
