/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A representation of a physical service area, a group of tables, in a restaurant.
 */
export interface ServiceArea extends HotschedulesToast.config.ToastReference {
    /** The name of this service area. */
    name?: string;
    revenueCenter?: HotschedulesToast.config.ExternalReference;
}
