/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetTimeEntryRequest {
    /**
     * Optional flag to indicate whether missed breaks should be
     * returned in the breaks array for the time entries.
     *
     */
    includeMissedBreaks?: boolean;
    /**
     * Controls whether the response includes an archived time entry.
     * Optional.
     *
     */
    includeArchived?: boolean;
    /**
     * The Toast platform GUID of the restaurant that is the
     * context for this operation.
     *
     */
    toastRestaurantExternalId: string;
}
