/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface AddItemsToACheckRequest {
    /**
     * The identifier of the restaurant.
     */
    toastRestaurantExternalId: string;
    body: HotschedulesToast.orders.Selection[];
}
