/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetMultipleOrdersRequest {
    /**
     * The inclusive start date and time. The results include orders with a modified date and time that occur at or after the `startDate`, but before the `endDate`. Use ISO-8601 format for the date and time, including a decimal fraction of a second. For example, `2016-01-01T14:13:12.000+0400`. URL encode the date and time value. The date must be after 2015-12-01T00:00:00.000+0000.
     *
     */
    startDate?: string;
    /**
     * The exclusive end date and time. The results exclude any orders that have a modified date and time that occurs at or after `endDate`. Use ISO-8601 format for the date and time, including a decimal fraction of a second. For example, `2016-01-01T14:13:12.000+0400`. URL encode the date and time value. The `endDate` date and time must be later than the `startDate` parameter value.
     *
     */
    endDate?: string;
    /**
     * The business date that same-day orders opened or that
     * scheduled orders are promised, in the format `yyyymmdd`.
     * The business day of an order is determined by the time the
     * order is opened or promised in the local time zone, and the
     * restaurant's business day cutoff time, which is available
     * from  the `General` object of the restaurants API in the
     * `closeoutHour` property.
     *
     */
    businessDate?: string;
    /**
     * The maximum number of objects to return in the array. If the number of objects selected by your request is greater than the `pageSize`, the API uses response pagination for the remaining objects. The maximum `pageSize` is `100`. For more information, see [the _Toast Developer Guide_](https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html).
     *
     */
    pageSize?: number;
    /**
     * The sequence number of the set of objects to return in paginated response data. For example, if you set the `pageSize` parameter to `10`, and you set `page` to `2`, the API returns a set of objects that starts with the eleventh object. For more information, see [the _Toast Developer Guide_](https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html).
     *
     */
    page?: number;
    /**
     * The identifier for the restaurant that processed the orders.
     *
     */
    toastRestaurantExternalId: string;
}
