/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetOrderIdentifiersDeprecatedRequest {
    /**
     * \ The inclusive start date and time. The results exclude orders with an earlier modified date and time. Use ISO-8601 format for the date and time, including a decimal fraction of a second. For example, `2016-01-01T14:13:12.000+0400`. URL encode the date and time value. The date must be after 2015-12-01T00:00:00.000+0000.
     */
    startDate?: string;
    /**
     * The exclusive end date and time. The results exclude orders with an equal or later modified date and time. Use ISO-8601 format for the date and time, including a decimal fraction of a second. For example, `2016-01-01T14:13:12.000+0400`. URL encode the date and time value. The `endDate` date and time must be later than the `startDate` parameter value.
     *
     */
    endDate?: string;
    /**
     * The business date that same-day orders opened or that scheduled orders are promised, in the format `yyyyMMdd`. The business day of an order is determined by the time the order is opened or promised in the local time zone, and by the restaurant's business day cutoff time, which is available from  the `General` object of the restaurants API in the `closeoutHour` property.
     *
     */
    businessDate?: string;
    /**
     * The identifier for the restaurant to retrieve orders from.
     */
    toastRestaurantExternalId: string;
}
