/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface PostAnOrderRequest {
    /**
     * The identifier for the restaurant where this order was placed.
     */
    toastRestaurantExternalId: string;
    body: HotschedulesToast.orders.Order;
}
