/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.labor.employees.getAll.Response.Raw,
    HotschedulesToast.labor.Employee[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../../../..")).labor.Employee));

export declare namespace Response {
    type Raw = serializers.labor.Employee.Raw[];
}
