/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Represents a dining table in a restaurant.
 */
export interface Table extends HotschedulesToast.config.ToastReference {
    /** The human-readable name of this table as it appears in the POS. */
    name?: string;
    serviceArea?: HotschedulesToast.config.ToastReference;
    revenueCenter?: HotschedulesToast.config.ExternalReference;
}
