/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * The overriding job wage, for an employee that has a wage that
 * differs from the job's default wage.
 *
 */
export interface JobWageOverride {
    /**
     * Required currency value of the employee's overriding job wage.
     *
     */
    wage: number;
    jobReference: HotschedulesToast.labor.ExternalReference;
}
