/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetAPaymentRequest {
    /**
     * The GUID of the restaurant used as the context of the request.
     */
    toastRestaurantExternalId: string;
}
