/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteEmployeeRequest {
    /**
     * The Toast platform GUID of the restaurant that is the
     * context for this operation.
     *
     */
    toastRestaurantExternalId: string;
}
