/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Job: core.serialization.ObjectSchema<serializers.labor.Job.Raw, HotschedulesToast.labor.Job> =
    core.serialization
        .object({
            createdDate: core.serialization.string().optional(),
            modifiedDate: core.serialization.string().optional(),
            deletedDate: core.serialization.string().optional(),
            title: core.serialization.string().optional(),
            deleted: core.serialization.boolean().optional(),
            wageFrequency: core.serialization
                .lazy(async () => (await import("../../../../..")).labor.WageFrequency)
                .optional(),
            defaultWage: core.serialization.number().optional(),
            tipped: core.serialization.boolean().optional(),
            code: core.serialization.string().optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).labor.ExternalReference));

export declare namespace Job {
    interface Raw extends serializers.labor.ExternalReference.Raw {
        createdDate?: string | null;
        modifiedDate?: string | null;
        deletedDate?: string | null;
        title?: string | null;
        deleted?: boolean | null;
        wageFrequency?: serializers.labor.WageFrequency.Raw | null;
        defaultWage?: number | null;
        tipped?: boolean | null;
        code?: string | null;
    }
}
