/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A set of ServiceAreas and POS devices for which separate revenue reports can be generated. For instance, a restaurant with a bar might choose to define two RevenueCenters, one for the bar and one for the dining area.
 */
export interface RevenueCenter extends HotschedulesToast.config.ToastReference {
    /** The name of this revenue center. */
    name?: string;
    /** The description of this revenue center. */
    description?: string;
}
