/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A wrapper object for the response to a successful Toast API authentication
 * request.
 *
 */
export interface AuthenticationResponse {
    token?: HotschedulesToast.auth.AuthenticationToken;
    /** The value `SUCCESS` indicates that your authentication request was successful. */
    status?: string;
}
