/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A discount configured in the Toast administration back-end.
 * Discounts are always applied before taxes, but after
 * service charges are calculated.
 *
 */
export interface Discount extends HotschedulesToast.config.ToastReference {
    /** The human-readable name of the discount. */
    name?: string;
    /**
     * Indicates whether the discount is available and can be
     * applied by restaurant employees.
     *
     */
    active?: boolean;
    /**
     * * `PERCENT` - the discount reduces the price by a
     * preconfigured percent.
     * * `FIXED` - the discount reduces the price by a
     * preconfigured currency amount.
     * * `OPEN_PERCENT` - the discount reduces the price by a
     * percent entered by a restaurant employee.
     * * `OPEN_FIXED` - the discount reduces the price by a
     * currency amount entered by a restaurant employee.
     * * `BOGO` - a buy one get one (BOGO) discount.
     * * `FIXED_TOTAL` - a combo discount that reduces the
     * price of all eligible items to a preconfigured currency
     * amount.
     *
     */
    type?: HotschedulesToast.config.DiscountType;
    /**
     * Percent discount applied when the `amountType` is
     * `PERCENT`. This value will be greater than 0 and at
     * most 100.
     *
     */
    percentage?: number;
    /**
     * The currency amount of the discount when the
     * `amountType` is `FIXED`. This value will be greater
     * than 0.
     *
     */
    amount?: number;
    /**
     * * `CHECK` - the discount can be applied to a check.
     * * `BOGO` - a buy one get one (BOGO) discount.
     * * `ITEM` - the discount can be applied to an item
     * selection in a check.
     *
     */
    selectionType?: HotschedulesToast.config.DiscountSelection;
    /**
     * Indicates whether you can apply the discount with other
     * discounts. This value is always `false` for item and
     * combo discounts. Set this value for check and BOGO
     * discounts by selecting **Allow with other discounts** in
     * the **Discounts Rules** section of the discounts
     * configuration page of the Toast administration
     * back-end.
     *
     */
    nonExclusive?: boolean;
    /**
     * Indicates which menu item selections are discounted
     * when you apply a BOGO discount. An item that is
     * discounted by a BOGO discount is a "get" item.
     * * `FIRST` - the BOGO discount applies to the first
     * matching item selection in the check or the discount is
     * not a BOGO discount. The `itemPickingPriority` is
     * always `FIRST` for discounts that are not BOGO
     * discounts.
     * * `LEAST_EXPENSIVE` - the BOGO discount applies
     * to the least expensive matching item selection in the check.
     * * `MOST_EXPENSIVE` - the BOGO discount applies to the most
     * expensive matching item selection in the check.
     *
     */
    itemPickingPriority?: HotschedulesToast.config.MenuSelection;
    /**
     * The total price of items discounted by a combo
     * discount. This value is `null` for discounts that are
     * not combo discounts.
     *
     */
    fixedTotal?: number;
}
