/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates which menu item selections are discounted
 * when you apply a BOGO discount. An item that is
 * discounted by a BOGO discount is a "get" item.
 * * `FIRST` - the BOGO discount applies to the first
 * matching item selection in the check or the discount is
 * not a BOGO discount. The `itemPickingPriority` is
 * always `FIRST` for discounts that are not BOGO
 * discounts.
 * * `LEAST_EXPENSIVE` - the BOGO discount applies
 * to the least expensive matching item selection in the check.
 * * `MOST_EXPENSIVE` - the BOGO discount applies to the most
 * expensive matching item selection in the check.
 *
 */
export type MenuSelection = "FIRST" | "LEAST_EXPENSIVE" | "MOST_EXPENSIVE";

export const MenuSelection = {
    First: "FIRST",
    LeastExpensive: "LEAST_EXPENSIVE",
    MostExpensive: "MOST_EXPENSIVE",
} as const;
