/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A wrapper object with fields that allow reference to a Toast
 * platform entity by Toast GUID or an external identifier.
 *
 */
export interface ExternalReference extends HotschedulesToast.labor.ToastReference {
    /**
     * External identifier string that is prefixed by the naming
     * authority. You can, for example, use the labor API to
     * `POST` an `externalId` for an employee and then `GET` the
     * employee with that `externalId`.
     *
     */
    externalId?: string;
}
