/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A conditional tax rate that overrides the default `rate`
 * for a `TaxRate` in
 * specific situations. For example, a conditional rate
 * might override the default rate when a `TaxRate` is
 * applied for a specific dining option, such as takeout.
 *
 */
export interface ConditionalTaxRate {
    /** A string describing the condition for the tax rate */
    condition?: string;
    /** The percentage rate of the conditional tax rate */
    rate?: number;
}
