/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A wrapper object with fields that allow reference to a Toast entity by Toast GUID or a partner's identifier.
 */
export interface ExternalReference extends HotschedulesToast.config.ToastReference {
    /** External identifier string, prefixed by the naming authority. */
    externalId?: string;
}
