/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information about an image associated with a menu or menu item.
 */
export interface Image {
    /** The web address of the image. */
    url?: string;
}
