/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The method used to round fractional currency amounts to non-fractional currency amounts. Only applies to `PERCENT` tax rates. For other tax rate types, `roundingType` is `null`. Valid values: * `HALF_UP` - Round values up or down to the nearest number. If the last digit is 5, which is halfway, then always round up to the nearest number. * `HALF_EVEN` - Round values up or down to the nearest number. If the last digit is 5, which is halfway, then round up or down to the nearest even number. * `ALWAYS_UP` - Always round up to the next number. * `ALWAYS_DOWN` - Always round down to the next number. For more details and examples, see <a href="https://doc.toasttab.com/doc/platformguide/adminPercentTaxRates.html#roundingOptions">Rounding options</a>.
 *
 */
export type RoundCurrencyMethod = "HALF_UP" | "HALF_EVEN" | "ALWAYS_UP" | "ALWAYS_DOWN";

export const RoundCurrencyMethod = {
    HalfUp: "HALF_UP",
    HalfEven: "HALF_EVEN",
    AlwaysUp: "ALWAYS_UP",
    AlwaysDown: "ALWAYS_DOWN",
} as const;
