/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of the tax rate.
 */
export type TaxRateType = "PERCENT" | "FIXED" | "TABLE" | "NONE" | "EXTERNAL";

export const TaxRateType = {
    Percent: "PERCENT",
    Fixed: "FIXED",
    Table: "TABLE",
    None: "NONE",
    External: "EXTERNAL",
} as const;
