/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A closed sale amount range that corresponds to a specific tax amount in a tax table.
 */
export interface TaxTableRow {
    /** The start of a sale amount range that corresponds to a specific tax amount in a tax table. */
    start?: number;
    /** The end of a sale amount range that corresponds to a specific tax amount in a tax table. */
    end?: number;
    /** The tax amount for the tax table row. */
    tax?: number;
    /** Specifies whether the price range is part of an incomplete set of ranges that establish an algorithm that you can use to calculate tax amounts. */
    pattern?: boolean;
}
