/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const DiningOption: core.serialization.ObjectSchema<
    serializers.config.DiningOption.Raw,
    HotschedulesToast.config.DiningOption
> = core.serialization
    .object({
        name: core.serialization.string().optional(),
        behavior: core.serialization
            .lazy(async () => (await import("../../../../..")).config.DiningOptionBehavior)
            .optional(),
        curbside: core.serialization.boolean().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).config.ExternalReference));

export declare namespace DiningOption {
    interface Raw extends serializers.config.ExternalReference.Raw {
        name?: string | null;
        behavior?: serializers.config.DiningOptionBehavior.Raw | null;
        curbside?: boolean | null;
    }
}
