/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * A wrapper object that contains information about a discount that you
 * can apply to an order, and which checks or menu item selections
 * you can apply it to.
 *
 */
export interface ApplicableDiscount {
    discount: HotschedulesToast.orders.ToastReference;
    /**
     * If the discount is applicable to a check, this value holds an array of `ExternalReference` objects containing the identifiers of the checks.
     *
     */
    applicableChecks?: HotschedulesToast.orders.ExternalReference[];
    /**
     * If the discount is applicable to a menu item selection, this
     * value holds an array of `ExternalReference` objects containing
     * the identifiers of the menu items.
     *
     */
    applicableSelections?: HotschedulesToast.orders.ExternalReference[];
}
