/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Authentication credentials for your Toast API integration client software.
 *
 */
export interface AuthenticationRequest {
    /**
     * The identifier string for your Toast API client. You receive the
     * identifier string from the Toast integrations team.
     *
     */
    clientId?: string;
    /**
     * The secret string that corresponds to your Toast API client. You
     * receive the secret string from the Toast integrations team.
     *
     */
    clientSecret?: string;
    /**
     * Always include the `userAccessType` value and set it to
     * `TOAST_MACHINE_CLIENT`.
     *
     */
    userAccessType?: string;
}
