/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Employee: core.serialization.ObjectSchema<
    serializers.labor.Employee.Raw,
    HotschedulesToast.labor.Employee
> = core.serialization
    .object({
        createdDate: core.serialization.string().optional(),
        modifiedDate: core.serialization.string().optional(),
        deletedDate: core.serialization.string().optional(),
        firstName: core.serialization.string().optional(),
        chosenName: core.serialization.string().optional(),
        lastName: core.serialization.string().optional(),
        email: core.serialization.string().optional(),
        phoneNumber: core.serialization.string().optional(),
        passcode: core.serialization.string().optional(),
        externalEmployeeId: core.serialization.string().optional(),
        deleted: core.serialization.boolean().optional(),
        disabled: core.serialization.boolean().optional(),
        jobReferences: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../../../..")).labor.ExternalReference))
            .optional(),
        wageOverrides: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../../../..")).labor.JobWageOverride))
            .optional(),
        v2EmployeeGuid: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).labor.ExternalReference));

export declare namespace Employee {
    interface Raw extends serializers.labor.ExternalReference.Raw {
        createdDate?: string | null;
        modifiedDate?: string | null;
        deletedDate?: string | null;
        firstName?: string | null;
        chosenName?: string | null;
        lastName?: string | null;
        email?: string | null;
        phoneNumber?: string | null;
        passcode?: string | null;
        externalEmployeeId?: string | null;
        deleted?: boolean | null;
        disabled?: boolean | null;
        jobReferences?: serializers.labor.ExternalReference.Raw[] | null;
        wageOverrides?: serializers.labor.JobWageOverride.Raw[] | null;
        v2EmployeeGuid?: string | null;
    }
}
