/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const JobWageOverride: core.serialization.ObjectSchema<
    serializers.labor.JobWageOverride.Raw,
    HotschedulesToast.labor.JobWageOverride
> = core.serialization.object({
    wage: core.serialization.number(),
    jobReference: core.serialization.lazyObject(async () => (await import("../../../../..")).labor.ExternalReference),
});

export declare namespace JobWageOverride {
    interface Raw {
        wage: number;
        jobReference: serializers.labor.ExternalReference.Raw;
    }
}
