/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Request: core.serialization.Schema<
    serializers.orders.orders.addItemToCheck.Request.Raw,
    HotschedulesToast.orders.Selection[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../../../..")).orders.Selection)
);

export declare namespace Request {
    type Raw = serializers.orders.Selection.Raw[];
}
