/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.orders.orders.getBulkOrders.Response.Raw,
    HotschedulesToast.orders.Order[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../../../..")).orders.Order));

export declare namespace Response {
    type Raw = serializers.orders.Order.Raw[];
}
