/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const MenuOptionGroup: core.serialization.ObjectSchema<
    serializers.config.MenuOptionGroup.Raw,
    HotschedulesToast.config.MenuOptionGroup
> = core.serialization
    .object({
        name: core.serialization.string().optional(),
        options: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../../../..")).config.ExternalReference))
            .optional(),
        minSelections: core.serialization.number().optional(),
        maxSelections: core.serialization.number().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).config.ExternalReference));

export declare namespace MenuOptionGroup {
    interface Raw extends serializers.config.ExternalReference.Raw {
        name?: string | null;
        options?: serializers.config.ExternalReference.Raw[] | null;
        minSelections?: number | null;
        maxSelections?: number | null;
    }
}
