/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AlternativePaymentTypeRequest {
    /**
     * The Toast POS GUID of the restaurant that the alternate payment
     * type is configured for.
     *
     */
    toastRestaurantExternalId: string;
}
