/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information about the last date and time that this restaurant's menu data was updated.
 *
 */
export interface Metadata {
    /**
     * A unique identifier for this restaurant, assigned by the Toast POS system.
     *
     */
    restaurantGuid?: string;
    /**
     * The most recent date and time that this menu's data was published. Use this value to determine if you need to refresh your menu data. The `lastUpdated` value uses the absolute timestamp format describe in the <a href="https://doc.toasttab.com/doc/devguide/api_dates_and_timestamps.html">Dates and timestamps</a> section of the Toast Developer Guide.
     *
     */
    lastUpdated?: string;
}
