/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specifies how the modifier group appears and behaves in the Toast POS app. Values include:
 *   * REQUIRED: Forces a server to make a selection from the modifier group before continuing to the next screen in the Toast POS app. Note that the orders API rejects an order if a modifier option is not included for a modifier group whose `requiredMode` value is set to REQUIRED.
 *   * OPTIONAL FORCE SHOW: Prompts the server to view the modifier group but does not force them to choose a modifier option from it before continuing to the next screen in the Toast POS app. This setting is typically used for upselling.
 *   * OPTIONAL: The modifier group does not appear when an associated menu item is selected but the server can access it on the Toast POS app if necessary.
 *
 */
export type ModifierGroupBehavior = "REQUIRED" | "OPTIONAL_FORCE_SHOW" | "OPTIONAL";

export const ModifierGroupBehavior = {
    Required: "REQUIRED",
    OptionalForceShow: "OPTIONAL_FORCE_SHOW",
    Optional: "OPTIONAL",
} as const;
