/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A container for the modifier groups that can be applied to a portion of a menu item.
 *
 */
export interface Portion {
    /**
     * A descriptive name for this portion, for example, "1st Half" or "2nd Half".
     *
     */
    name?: string;
    /**
     * A unique identifier for this portion, assigned by the Toast POS system.
     *
     */
    guid?: string;
    /**
     * An array of `referenceId`s for `ModifierGroup` objects. These objects define the modifier groups that can be applied to this portion.
     *
     */
    modifierGroupReferences?: number[];
}
