/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information about a pre-modifier configured for this restaurant.
 *
 */
export interface PreModifier {
    /**
     * A descriptive name for this pre-modifier, for example, "NO" or "EXTRA".
     *
     */
    name?: string;
    /**
     * A unique identifier for this pre-modifier group, assigned by the Toast POS system.
     *
     */
    guid?: string;
    /**
     * An optional fixed price for this pre-modifier. The fixed price is added to the cost of the modifier option that the pre-modifier is applied to. A PreModifier object has two optional values, `fixedPrice` and `multiplicationFactor`, that both alter the price of a modifier option when the pre-modifier is applied to it. However, these values cannot be used at the same time. If you specify a `fixedPrice` value for a premodifier, then `multiplicationFactor` is null. If you specify a `multiplicationFactor` for a pre-modifier, then `fixedPrice` is null. If you choose not to assign either a fixed price or a multiplication factor to a pre-modifier, then the `fixedPrice` value is 0 and the `multiplicationFactor` is null.
     *
     */
    fixedPrice?: number;
    /**
     * An optional number that specifies how much the cost of a modifier option is multiplied by when this pre-modifier is applied to it. For example, an EXTRA pre-modifier option could specify a `multiplicationFactor` of 1.5 to indicate that adding extra cheese to a menu item costs one and a half times the regular price of the cheese modifier option. A PreModifier object has two optional values, `fixedPrice` and `multiplicationFactor`, that both alter the price of a modifier option when the pre-modifier is applied to it. However, these values cannot be used at the same time. If you specify a `fixedPrice` value for a premodifier, then `multiplicationFactor` is null. If you specify a `multiplicationFactor` for a premodifier, then `fixedPrice` is null. If you choose not to assign either a fixed price or a multiplication factor to a pre-modifier, then the `fixedPrice` value is 0 and the `multiplicationFactor` is null.
     *
     */
    multiplicationFactor?: number;
    /**
     * A string that indicates how the pre-modifier is displayed on tickets and receipts:
     *   * PREFIX: The pre-modifier name is placed before the modifier option name, for example, "EXTRA Cheese".
     *   * SUFFIX: The pre-modifier name is placed after the modifier option name, for example, "Cheese EXTRA".
     *
     */
    displayMode?: HotschedulesToast.menus.PreModifierDisplay;
}
