/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information about a pre-modifier group configured for this restaurant, including an array of pre-modifiers contained in the group.
 *
 */
export interface PreModifierGroup {
    /**
     * A descriptive name for this pre-modifier group, for example, "Sandwich Pre-mods".
     *
     */
    name?: string;
    /**
     * A unique identifier for this pre-modifier group, assigned by the Toast POS system.
     *
     */
    guid?: string;
    /**
     * An array of `PreModifier` objects that are contained in this pre-modifier group. Pre-modifiers alter the display of modifier options on receipts and tickets to satisfy guest requests such as EXTRA or ON THE SIDE for modifier options. Pre-modifiers can also be configured to modify the cost of the modifier options they are applied to, for example, by charging more for an EXTRA serving of a modifier option.
     *
     */
    preModifiers?: HotschedulesToast.menus.PreModifier[];
}
