/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unit of measure used to determine the price of the item. For example, $10.00 per gram.
 *
 */
export type PriceUnit = "NONE" | "LB" | "OZ" | "KG" | "G";

export const PriceUnit = {
    None: "NONE",
    Lb: "LB",
    Oz: "OZ",
    Kg: "KG",
    G: "G",
} as const;
