/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Information about the restaurant whose menu data has been retrieved.
 *
 */
export interface Restaurant {
    /**
     * A unique identifier for this restaurant, assigned by the Toast POS system.
     *
     */
    restaurantGuid?: string;
    /**
     * The most recent date and time that this menu's data was published. Use this value to determine if you need to refresh your menu data. The `lastUpdated` value uses the absolute timestamp format describe in the <a href="https://doc.toasttab.com/doc/devguide/api_dates_and_timestamps.html">Dates and timestamps</a> section of the Toast Developer Guide.
     *
     */
    lastUpdated?: string;
    /**
     * The name of the restaurant's time zone in the IANA time zone database https://www.iana.org/time-zones. For example, "America/New_York".
     *
     */
    restaurantTimeZone?: string;
    /**
     * An array of `Menu` objects that represent the published menus used by this restaurant.
     *
     */
    menus?: HotschedulesToast.menus.Menu[];
    /**
     * A map of `ModifierGroup` objects that define the modifier groups used by this restaurant. Each `ModifierGroup` object is presented as a key/value pair. A pair's key matches the `referenceId` of the object contained in the pair's value, as shown below: ```
     *   "modifierGroupReferences": {
     *     ...
     *     "3": {
     *       "referenceId": 3,
     *       "name": "Toppings",
     *       "guid": "58b79986-f88f-411d-ba18-14b1e2441e9d",
     *         ...
     *       },
     *       ...
     *       "modifierOptionReferences": [
     *         10,
     *         11
     *       ],
     *       ...
     *     },
     *     ...
     *   },
     * ``` Other menu entities refer to modifier groups using their `referenceId`. Having a key that matches the `referenceId` allows you to locate the correct modifier group in the `modifierGroupReferences` map. For more information on the `referenceId` value, see the <a href="https://doc.toasttab.com/doc/devguide/apiUnderstandingGuidsEntityIdentifiersAndMultilocationIds_V2.html">Understanding GUIDs, referenceIds, and multilocationIds</a> section of the Toast Developer Guide.
     *
     */
    modifierGroupReferences?: Record<string, HotschedulesToast.menus.ModifierGroup | undefined>;
    /**
     * A map of `ModifierOption` objects that define the modifier options used by this restaurant. Each `ModifierOption` object is presented as a key/value pair. A pair's key matches the `referenceId` of the object contained in the pair's value, as shown below: ``` "modifierOptionReferences": {
     *   ...
     *   "10": {
     *     "referenceId": 10,
     *     "name": "Mushrooms",
     *     "guid": "fa24fee9-76c4-40ba-ae3c-7dfccafdd8d3",
     *     ...
     *   },
     *   "11": {
     *     "referenceId": 11,
     *     "name": "Onions",
     *     "guid": "afee6be7-8280-4c69-a170-9fdf4c76bf7b",
     *     ...
     *   },
     *   ...
     * } ``` Other menu entities refer to modifier options using their `referenceId`. Having a key that matches the `referenceId` allows you to locate the correct modifier option in the `modifierOptionReferences` map. For more information on the `referenceId` value, see the <a href="https://doc.toasttab.com/doc/devguide/apiUnderstandingGuidsEntityIdentifiersAndMultilocationIds_V2.html">Understanding GUIDs, referenceIds, and multilocationIds</a> section of the Toast Developer Guide.
     *
     */
    modifierOptionReferences?: Record<string, HotschedulesToast.menus.ModifierOption | undefined>;
    /**
     * A map of `PreModifierGroup` objects that define the premodifier groups used by this restaurant. Each `PreModifierGroup` object is presented as a key/value pair. A pair's key matches the `referenceId` of the object contained in the pair's value, as shown below: ``` "preModifierGroupReferences": {
     *   "22": {
     *     "referenceId": 22,
     *     "guid": "07a1a94d-6f7b-46d5-a916-a07fa16bb8e8",
     *     "name": "PreModGroup",
     *     "preModifiers": [
     *       {
     *         "guid": "ad45e697-9356-468e-b7b4-1b23f4d4b8a5",
     *         "name": "EXTRA",
     *         "fixedPrice": 1.0,
     *         "multiplicationFactor": null,
     *         "displayMode": "PREFIX"
     *       },
     *       {
     *         "guid": "483dd4cf-acea-4373-ae76-5f7efd0d529d",
     *         "name": "NO",
     *         "fixedPrice": 0.0,
     *         "multiplicationFactor": null,
     *         "displayMode": "PREFIX"
     *       }
     *     ]
     *   },
     * },             ``` Other menu entities refer to premodifier groups using their `referenceId`. Having a key that matches the `referenceId` allows you to locate the correct premodifier group in the `preModifierGroupReferences` map. For more information on the `referenceId` value, see the <a href="https://doc.toasttab.com/doc/devguide/apiUnderstandingGuidsEntityIdentifiersAndMultilocationIds_V2.html">Understanding GUIDs, referenceIds, and multilocationIds</a> section of the Toast Developer Guide.
     *
     */
    preModifierGroupReferences?: Record<string, HotschedulesToast.menus.PreModifierGroup | undefined>;
}
