/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A descriptive category, for example, "Food" or "Liquor" that, when applied to the menu items and modifier options in your menu, allow you to view sales data by category. Null if no sales category has been defined.
 *
 */
export interface SalesCategory {
    /**
     * A descriptive name for this sales category, for example, "Food" or "Liquor".
     *
     */
    name?: string;
    /**
     * A unique identifier for this sales category, assigned by the Toast POS system.
     *
     */
    guid?: string;
}
