/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

/**
 * Represents the pricing rules for a menu item that uses a time-specific price.
 *
 */
export interface TimeSpecificPrice {
    /**
     * The price of the menu item during the periods of time defined by the associated `schedule` array.
     *
     */
    timeSpecificPrice?: number;
    /**
     * The base price of the menu item, used for time periods when a time-specific price has not been defined.
     *
     */
    basePrice?: number;
    /**
     * An array of `Schedule` objects that indicate the specific days and times that a time-specific price is available.
     *
     */
    schedule?: HotschedulesToast.menus.Schedule[];
}
