/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents a time range for when a menu or a time-specific price is available.
 *
 */
export interface TimeRange {
    /**
     * The start time of the time range. Expressed in the restaurant’s local time.
     *
     */
    start?: string;
    /**
     * The end time of the time range. Expressed in the restaurant’s local time.
     *
     */
    end?: string;
}
