/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const PreModifierPlacement: core.serialization.Schema<
    serializers.config.PreModifierPlacement.Raw,
    HotschedulesToast.config.PreModifierPlacement
> = core.serialization.enum_(["PREFIX", "SUFFIX"]);

export declare namespace PreModifierPlacement {
    type Raw = "PREFIX" | "SUFFIX";
}
