/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BreakTypeRequest {
    /**
     * The Toast POS GUID of the restaurant that the break is configured for.
     *
     */
    toastRestaurantExternalId: string;
}
