/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { HotschedulesToast } from "@fern-api/toast";
import * as core from "../../../../../../core";

export const Table: core.serialization.ObjectSchema<serializers.config.Table.Raw, HotschedulesToast.config.Table> =
    core.serialization
        .object({
            name: core.serialization.string().optional(),
            serviceArea: core.serialization
                .lazyObject(async () => (await import("../../../../..")).config.ToastReference)
                .optional(),
            revenueCenter: core.serialization
                .lazyObject(async () => (await import("../../../../..")).config.ExternalReference)
                .optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).config.ToastReference));

export declare namespace Table {
    interface Raw extends serializers.config.ToastReference.Raw {
        name?: string | null;
        serviceArea?: serializers.config.ToastReference.Raw | null;
        revenueCenter?: serializers.config.ExternalReference.Raw | null;
    }
}
