/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { HotschedulesToast } from "@fern-api/toast";

export interface AlternatePaymentType extends HotschedulesToast.config.ExternalReference {
    /** The name of the alternate payment type. */
    name?: string;
}
